# Módulo calidad_datos - LEILA
Este libro de Jupyter contiene ejemplos con explicaciones de cómo utilizar el módulo que presenta métricas de calidad y descriptivas para conjuntos de datos estructurados

In [1]:
# Se importar la clase CalidadDatos del módulo calidad_datos

import pandas as pd
import numpy as np

#### Se importan los csvs

In [2]:
# se importan los csvs

df = pd.read_csv('C:\\Users\\20927322707\\Desktop\\analizador_datasets\\csv\\actuaciones-fiscalizacion\\contribuyentes-bajo-inspeccion-3-trimestre-2015.csv', sep=',', encoding='utf-8')

In [3]:
# se visualizan las principales características del dataset , como su metadata y la completitud y calidad de los datos

print("-------------------------")
print("Infomración principal del dataset")
print("-------------------------")
print(df.info())

# calcular la completitud de los datos

completitud_df = df.count() / len(df) * 100
completitud_df = completitud_df.sort_values(ascending=False)

print("-------------------------")
print("Completitud de los datos")
print("-------------------------")
print(completitud_df)


print("-------------------------")
print("Estas son las dimensiones del dataset")
print("-------------------------")
print("Filas: {}".format(df.shape[0]))
print("Columnas: {}".format(df.shape[1]))
print("-------------------------")
# print("Estas son las estadisticas del dataset")
# print(df.describe())
print("-------------------------")
print("Primeras 5 filas del dataset")
print("-------------------------")
print(df.head(5))
print("-------------------------")
print("Estas son las filas duplicadas del dataset")
print("-------------------------")
print(df.duplicated().sum())    
print("-------------------------")
print("Valores unicos")
print("-------------------------")
print(df.nunique())
print("-------------------------")  
print("Valores nulos")    
print("-------------------------")
print(df.isna().sum())
print("-------------------------")
print("Tipos de datos")
print("-------------------------")
print(df.dtypes)


if df.select_dtypes(include=['object']).shape[1] > 0:
    print("El dataset contiene variables categóricas")
    print("-------------------------") 
    print("Variables categóricas")
    print("-------------------------")
    print(df.select_dtypes(include=['object']).columns)
    print("-------------------------")
    print("Valores únicos de las variables categóricas")
    print("-------------------------")
    print(df.select_dtypes(include=['object']).nunique())

else:
    print("El dataset no contiene variables categóricas")


valores_unicos_categoricos =  df.select_dtypes(include=['object']).nunique()

print("-------------------------")
print("Valores únicos de las variables categóricas")
print("-------------------------")
print(valores_unicos_categoricos)

-------------------------
Infomración principal del dataset
-------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1945 entries, 0 to 1944
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NUM_ORDEN           1945 non-null   int64
 1   DEPARTAMENTO        1945 non-null   object
 2   DIVISION            1669 non-null   object
 3   INSPECTOR           1945 non-null   object
 4   SUPERVISOR          1935 non-null   object
 5   CUIT                1945 non-null   object
 6   RAZON_SOCIAL        1945 non-null   object
 7   FECHA_INICIO        1936 non-null   object
 8   FECHA_DEVOL_TRANSF  277 non-null    object
dtypes: int64(1), object(8)
memory usage: 136.9+ KB
None
-------------------------
Completitud de los datos
-------------------------
NUM_ORDEN             100.000000
DEPARTAMENTO          100.000000
INSPECTOR             100.000000
CUIT                  100.000000
RAZON_SOCIAL          100.000000
FECHA_INICIO           99.537275
SUPERVISOR             99.485861
DIVISION               85.809769
FECHA_DEVOL_TRANSF     14.241645
dtype: float64
-------------------------
Estas son las dimensiones del dataset
-------------------------
Filas: 1945
Columnas: 9
-------------------------
-------------------------
Primeras 5 filas del dataset
-------------------------
   NUM_ORDEN                                   DEPARTAMENTO DIVISION  \
0          1                                      EXTERNA E        I
1          2  PUBLICIDAD, REG. SIMPL. DEL ISIB Y OPERATIVOS        B
2          3                                      EXTERNA D   SELLOS
3          4                                      EXTERNA B        5
4          5                                      EXTERNA A        2

              INSPECTOR         SUPERVISOR         CUIT  \
0          CRESPO ARIEL      PATANE ALICIA  30710240244
1       CARDONE MARIANO  ZOCCALI JOSE LUIS  33707083129
2       LANFRANCO PABLO       ALFARO NADIA  30529994393
3  SICILIANO MARIA ROSA      CAPUTO ROMINA  30708826568
4       PERALTA MARCELA     ALVAREZ MARTIN  30708449853

                           RAZON_SOCIAL FECHA_INICIO FECHA_DEVOL_TRANSF
0                        1001 FARDO SRL   01/10/2014                NaN
1                           25 HORAS SA   27/03/2015                NaN
2                  3M ARGENTINA SACIFIA   23/12/2013         19/08/2015
3  4 M SOCIEDAD DE RESPONSABILIDAD LTDA          N/L                NaN
4                       5TH ESSENCE S.A   09/02/2015                NaN
-------------------------
Estas son las filas duplicadas del dataset
-------------------------
0
-------------------------
Valores unicos
-------------------------
NUM_ORDEN             1945
DEPARTAMENTO            12
DIVISION                20
INSPECTOR              319
SUPERVISOR              65
CUIT                  1928
RAZON_SOCIAL          1938
FECHA_INICIO           499
FECHA_DEVOL_TRANSF     147
dtype: int64
-------------------------
Valores nulos
-------------------------
NUM_ORDEN                0
DEPARTAMENTO             0
DIVISION               276
INSPECTOR                0
SUPERVISOR              10
CUIT                     0
RAZON_SOCIAL             0
FECHA_INICIO             9
FECHA_DEVOL_TRANSF    1668
dtype: int64
-------------------------
Tipos de datos
-------------------------
NUM_ORDEN              int64
DEPARTAMENTO          object
DIVISION              object
INSPECTOR             object
SUPERVISOR            object
CUIT                  object
RAZON_SOCIAL          object
FECHA_INICIO          object
FECHA_DEVOL_TRANSF    object
dtype: object
El dataset contiene variables categóricas
-------------------------
Variables categóricas
-------------------------
Index(['DEPARTAMENTO', 'DIVISION', 'INSPECTOR', 'SUPERVISOR', 'CUIT',
       'RAZON_SOCIAL', 'FECHA_INICIO', 'FECHA_DEVOL_TRANSF'],
      dtype='object')
-------------------------
Valores únicos de las variables categóricas
-------------------------
DEPARTAMENTO            12
DIVISION                20
INSPECTOR              319
SUPERVISOR              65
CUIT                  1928
RAZON_SOCIAL          1938
FECHA_INICIO           499
FECHA_DEVOL_TRANSF     147
dtype: int64
-------------------------
Valores únicos de las variables categóricas
-------------------------
DEPARTAMENTO            12
DIVISION                20
INSPECTOR              319
SUPERVISOR              65
CUIT                  1928
RAZON_SOCIAL          1938
FECHA_INICIO           499
FECHA_DEVOL_TRANSF     147
dtype: int64

In [4]:
import pandas as pd
import numpy as np 

# Obtener los valores únicos de las variables categóricas

# Seleccionar las variables categóricas

valores_categoricos = df.select_dtypes(include=['object'])  # Seleccionar las variables categóricas

print(valores_categoricos)

valores_categoricos = pd.DataFrame(valores_categoricos) # Convertir las variables categóricas en un DataFrame

valores_categoricos_dataframe = valores_categoricos.nunique()

print(valores_categoricos_dataframe)

                                       DEPARTAMENTO DIVISION  \
0                                         EXTERNA E        I
1     PUBLICIDAD, REG. SIMPL. DEL ISIB Y OPERATIVOS        B
2                                         EXTERNA D   SELLOS
3                                         EXTERNA B        5
4                                         EXTERNA A        2
...                                             ...      ...
1940                           CONCURSOS Y QUIEBRAS      NaN
1941                                      EXTERNA E        I
1942                                     OPERATIVOS        A
1943                                      EXTERNA D   SELLOS
1944                                      EXTERNA C        8

                 INSPECTOR           SUPERVISOR           CUIT  \
0             CRESPO ARIEL        PATANE ALICIA    30710240244
1          CARDONE MARIANO    ZOCCALI JOSE LUIS    33707083129
2          LANFRANCO PABLO         ALFARO NADIA    30529994393
3     SICILIANO MARIA ROSA        CAPUTO ROMINA    30708826568
4          PERALTA MARCELA       ALVAREZ MARTIN    30708449853
...                    ...                  ...            ...
1940        CRISPINO PAULO    GIAMMARCHE DANIEL  30-65461789-5
1941         IBARRA CARLOS       FERNANDEZ JUAN  30-68077909-7
1942     ROUSSEAUX JULIETA       GONZALEZ MAURO  27-18874058-3
1943       LANFRANCO PABLO         ALFARO NADIA  30-69102170-6
1944         BAREIRO JUANA  SANCHEZ ARIAS HILDA  20-94161034-0

                              RAZON_SOCIAL FECHA_INICIO FECHA_DEVOL_TRANSF
0                           1001 FARDO SRL   01/10/2014                NaN
1                              25 HORAS SA   27/03/2015                NaN
2                     3M ARGENTINA SACIFIA   23/12/2013         19/08/2015
3     4 M SOCIEDAD DE RESPONSABILIDAD LTDA          N/L                NaN
4                          5TH ESSENCE S.A   09/02/2015                NaN
...                                    ...          ...                ...
1940              WORLD COLOR ARGENTINA SA   05/06/2015                NaN
1941                         WORLD GIFT SA   31/10/2014                NaN
1942                            WU YU LING   23/04/2015                NaN
1943                      WUNDER PHARM SRL   15/01/2015                NaN
1944                            XIA JINHUA   28/04/2015                NaN

[1945 rows x 8 columns]
DEPARTAMENTO            12
DIVISION                20
INSPECTOR              319
SUPERVISOR              65
CUIT                  1928
RAZON_SOCIAL          1938
FECHA_INICIO           499
FECHA_DEVOL_TRANSF     147
dtype: int64

In [6]:
import pandas as pd
import json

# Obtener los valores únicos de las variables categóricas

valores_unicos_por_categoria = {
    "valores_unicos": {
        columna: df[columna].unique().tolist()
        for columna in df.select_dtypes(include=['object'])
    }
}

with open('valores_unicos_contribuyentes', 'w') as f:      # Abrir un archivo JSON para guardar los valores únicos 'w' es para escribir with es para abrir y cerrar el archivo
    json.dump(valores_unicos_por_categoria, f, indent=4) # Guardar los valores únicos en un archivo JSON donde f es el archivo indent es la identación y dump es para guardar

valores_unicos_por_categoria

{'valores_unicos': {'DEPARTAMENTO': ['EXTERNA E',
   'PUBLICIDAD, REG. SIMPL. DEL ISIB Y OPERATIVOS',
   'EXTERNA D',
   'EXTERNA B',
   'EXTERNA A',
   'EXTERNA C',
   'EXTERNA F',
   'CONCURSOS Y QUIEBRAS',
   'OPERATIVOS',
   'PLANIFICACION Y SELECCION',
   'NORMAS Y MANUALES DE FISCALIZACION',
   'BANCOS'],
  'DIVISION': ['I',
   'B',
   'SELLOS',
   '5',
   '2',
   '7',
   '6',
   '10',
   '8',
   '1',
   nan,
   'A',
   '3',
   '4',
   'INTERNA I',
   '9',
   'MODULARES SELLOS',
   'II',
   'INTERNA II',
   'EQUIPO A',
   'BANCOS'],
  'INSPECTOR': ['CRESPO ARIEL',
   'CARDONE MARIANO',
   'LANFRANCO PABLO',
   'SICILIANO MARIA ROSA',
   'PERALTA MARCELA',
   'BERNALDO DE QUIROS ALVARO',
   'CODERCH ROCHE TATIANA',
   'RUA, CLAUDIA',
   'VALDES DAMIAN JAVIER',
   'SANTORO MARTIN',
   'PEDRO ROMINA',
   'IBARRA CARLOS',
   'ROJAS LORENA',
   'RIPOLI JORGE',
   'BODNER ALEJANDRA',
   'ANDREU DANIEL',
   'ABBEDUTO JUAN JOSE',
   'NOVOA NANCY',
   'IGLESIAS LILIANA',
   'MOYA JULIETA ANDREA',
   'PEREIRA VIVIANA',
   'SANTORO NESTOR',
   'CASSIS CLAUDIA',
   'FERRETTI CLAUDIA',
   'LIPARI GLADYS',
   'VILLEGAS CESAR',
   'KARIN EDUARDO DANIEL',
   'GODINO RUBEN',
   'SUEIRO FERNANDO',
   'FORTE M. FLORENCIA',
   'JULIO MARIANA',
   'BUJANDA ROMINA',
   'CASTILLO CAROLINA',
   'NOVOA MARIANA',
   'RIVAS GRACIELA',
   'MARI CRISTIAN',
   'ORTUBIA MABEL',
   'ERMILIO MARIA',
   'CIOCCA ELEONORA',
   'RODRIGUEZ, MONICA',
   'GUEVARA LIA',
   'RIVEIRA SERGIO',
   'SALMON SILVANA',
   'LOPEZ MARIA CAROLINA',
   'ROUSSEAUX JULIETA',
   'BURGOS ROSA M.',
   'AVALLONE MARIA LAURA',
   'LA VALLE MAURICIO',
   'ORTIZ BROSSARD IVANNA',
   'NIEMES GUILLERMO',
   'CALZONE ALEJANDRA',
   'COLOM SILVIA',
   'GARCIA LAURA',
   'YOCCO ELIDA ALICIA',
   'BOGO MORALES MARIANO',
   'MUNIZ CLAUDIO',
   'QUIROGA MARIA FLORENCIA',
   'ALSAMORA ALBERTO',
   'BASUALDO MARCELA',
   'PETRONE MARIA',
   'MOURELLE LAURA BEATRIZ',
   'ACHAGA PAOLA',
   'USAI GABRIELA',
   'DAGLIO DANIELA',
   'MALAGUEÑO, ELDA A.',
   'MAGNO ANALIA PAULA',
   'CHIUSANO SERGIO',
   'NAVARRO LAURA',
   'VAZQUEZ CLAUDIO',
   'STABILE ALEJANDRO',
   'DOMINGUEZ MARIA LUZ',
   'ANDRADA ELEONORA',
   "D'ANTUONO OSVALDO",
   'KOLINSKI LAURA',
   'BUTTAFUOCO, CESAR',
   'MARINO VIRGINIA',
   'ZALAZAR KARINA',
   'CONTRERAS MANUEL',
   'GRANDE GABRIEL',
   'DABUL ARIADNA C.',
   'MALDONADO SONIA',
   'DUBOWSKI DEBORA',
   'LOPEZ GUSTAVO',
   'OLIVERAS PATRICIA',
   'POMILIO MARIANA',
   'TRACCHIA EDUARDO',
   'SILVA ALICIA ITATI',
   'MESSINA ADRIANA NOEMI',
   'MARTIRE VERONICA',
   'CALZONE SERGIO',
   'COTELLA CLAUDIA',
   'PEZZELATO GABRIELA',
   'SIMUTIS ALEJANDRA',
   'RUBALDO DANIEL',
   'MOLINA VALERIA',
   'CARMONA GUSTAVO',
   'ALADRO, JORGE',
   'ONGARO JORGELINA',
   'LICASTRO JOSE',
   'FAVARO LUCIANA',
   'DI TIERI JUAN',
   'BUONO ANA',
   'WASSOUF GERMAN',
   'AGÜERO MONICA',
   'SAVI MARIA EUGENIA',
   'NALBANDIAN M. CRISTINA',
   'GONZALEZ CRISTINA',
   'NASELLI BRUNO',
   'ARAYA, JAVIER',
   'NACCARI LILIANA',
   'ORQUIN MARIA F',
   'COMI MARIO JORGE',
   'BADRA JORGE',
   'ROSSO ELENA',
   'AQUINO NORBERTO',
   'SCHENONE MARIA OFELIA',
   'ALEGRE PAOLA',
   'AYERBE SILVIO',
   'GUTIERREZ GASTON',
   'VILAR LEANDRO',
   'KALEKA RUTH',
   'MESSINA SEBASTIAN',
   'CAPARRA MARCELA',
   'DE CUNTO VERONICA',
   'JURI VELIZ GISELA',
   'LONGHI SILVIA',
   'FERNANDEZ VAQUERA, B',
   'PENZA SILVINA',
   'MOOR LAURA CINTIA',
   'PACHECO MABEL',
   'CICCONE GISELA',
   'GUTIERREZ ALICIA',
   'PROCUPEZ CLAUDIO',
   'RIVERO TERRAZAS NOEMI',
   'TORRISI LUIS',
   'REZK FRANCISCO',
   'NATALE, VINCENZO',
   'BERNARDEZ CARLOS',
   'MERNES ELSIE',
   'NEGRETTI NANCY',
   'CHAIZAZ VALENZUELA TAMARA',
   'COGLIOLO ANALIA',
   'MOYA PATRICIA',
   'VALENZUELA LORENA',
   'BERNARDO ALICIA',
   'ALEGRE LUIS',
   'RODRIGUEZ ROBERTO',
   'CANDIA SILVIA',
   'MANDEL MARIO',
   'SILEO ANALIA',
   'CAMELINO SUSANA',
   'BORRI ROMINA',
   'LEDESMA CARINA',
   'ZANARDI CRISTINA',
   'CIGNONI ALEJANDRA',
   'ABUIN VERONICA',
   'ARAMAYO FERNANDO',
   'MORANO ADOLFO',
   'DICOSTA LILIA',
   'BAREIRO JUANA',
   'MERLO CESAR',
   'PEREZ MONICA',
   'DITURI ADRIANA',
   'BONAVITA MARCELA',
   'SZUMOWSKI CAROLINA',
   'MADELAIRE LUIS',
   'VUOTTO GUSTAVO',
   'AROZTEGUI PATRICIA',
   'RYSZNIVKIER JESICA',
   'ASMUS, MERCEDES',
   'MERA ANDREA',
   'NICOLINO ORNELA',
   'FERRARI JAVIER',
   'SGARBOSSA VALERIA',
   'FERRARO LAURA',
   'BOSANO VALERIA',
   'SANTORO SILVIA',
   'PEREYRA CYNTHIA',
   'FIASCHE RUBEN',
   'TRAVERSA NATALIA',
   'ESQUEFF ESTELA',
   'SANTOS, ANALIA',
   'FORTUNA MARIA LAURA',
   'FUERTES SANDRA',
   'VEGA DANIEL',
   'AJARGO LAURA',
   'CHICHIZOLA MARIA J.',
   'DRAGUNSKY MARCELO',
   'LENAGHAN OSVALDO',
   'BEITONE VANESA',
   'CHIRDO FLAVIA',
   'IRALA ELSA',
   'DE LUCA ANDREA',
   'BERNUES PLINIO',
   'ALEGRE SOLEDAD',
   'TORRE ANDREA',
   'AREN MARIA EVA',
   'DIAZ ERIKA',
   'LOPEZ KADAR MARCELO',
   'ALEGRE NATALIA',
   'TASSI LILIANA',
   'FERNANDEZ LAVIA JOAQUIN',
   'LOMBARDO VANESA',
   'ALVAREZ BEATRIZ',
   'SANSOLINI DIEGO',
   'VAINER PABLO',
   'PUGLIESE ADRIANA',
   'CRISPINO PAULO',
   'PATANE GRACIELA',
   'RUIZ, DANIEL ALBERTO',
   'TECAZINER LUIS',
   'OUTON JULIO',
   'ENTROCASSI PAOLA',
   'ROMANO DANIEL',
   'CAPUTO CARLOS',
   'ZALAZAR PAOLA',
   'SALDANERI GISELLA',
   'GROSSI GUILLERMO',
   'CERRUTI PATRICIA',
   'GONZALEZ LAURA',
   'CALVANI ALDANA',
   'DE LUSARRETA',
   'CLOCCHIATTI M. CECILIA',
   'BRONSTAIN JORGE',
   'ARRIETA SILVIA',
   'LESCANO MONICA',
   'PEREZ GUSTAVO',
   'MOSCOLONI MONICA',
   'DELL´AGNOLO FLORENCIA',
   'DUJO ANDREA FABIANA',
   'GARCIA PAOLA',
   'BENAVIDEZ MIRNA SAMANTA',
   'AGUIRRE FLAVIA',
   'BAJO HERNAN',
   'VARCHIONI ANDREA',
   'GOMEZ YAMILA',
   'MONZON GRACIELA',
   'BARLETTA PAULA',
   'BIANCO FIORELLA',
   'BELTRAMONE INES',
   'BLANCO RAUL',
   'ROMERO JORGE',
   'YAZRA ALDO',
   'BURGOS MARCELA',
   'BIANCHI CLAUDIO',
   'BIANCHI ADRIAN',
   'SALVADOR M. EUGENIA',
   'TROBO LAURA',
   'RADICE KARINA',
   'ZAPATA MARIA CECILIA',
   'SAGOL VALERIA',
   'TROTTA DIEGO',
   'MANCHINI PABLO',
   'GARCIA LINARES GERARDO',
   'BALZANO CARLOS',
   'ROMERO GERMAN',
   'PANTANO HORACIO',
   'REIST MARTA PATRICIA',
   'AGOSTINI MARIANA',
   'PONTI CLAUDIA',
   'GUANO NICOLAS',
   'GALVEZ GRISELDA',
   'DIAZ GLADYS',
   'CASTIGLIONE ROMINA',
   'RUIZ RICARDO',
   'SAAD FERNANDO',
   'PANELO CLAUDIA',
   'YANKELEVICH PABLO',
   'LOBO SILVIA MARIANA',
   'PRADO EVA',
   'SEDANO FERNANDA',
   'PERTA AURELIA',
   'MANGANARO CLAUDIO',
   'DEL RIO VERONICA',
   'VALENZUELA, EMMANUEL RODRIGO',
   'EXPOSITO JORGE',
   'FISCHER MARIA BELEN',
   'TROVATO ROMINA',
   'PALOMINO VERONICA',
   'SUAREZ MARIA',
   'DI RISIO DANIELA',
   'LAMANA ANALIA',
   'MALAMUT DIEGO JAVIER',
   'ETCHEVERRY FERNANDO',
   'LOMBARDI ROMINA',
   'VILLA STELLA MARIS',
   'NEME CAROLINA',
   'FERNANDEZ BEATRIZ',
   'BOTTOLI OSCAR',
   'CASTAÑEDA VIVIANA',
   'TORRISI GRISELDA',
   'MORANDO GUSTAVO',
   'GARCIA ARECHA LUIS',
   'ZARAGOCI SEBASTIAN',
   'OVIEDO KARINA',
   'PEREZ ROSANA',
   'BOGIN VERONICA',
   'TUSTANOSKI MARCELO',
   'BATTAGLIA ROSARIO',
   'YAÑEZ NORA',
   'CESTER DANIEL',
   'GOMEZ NELIDA',
   'VILLACORTA MARIA',
   'ZOILO JUAN',
   'SCARANO EMMANUEL',
   'FERREIRO NESTOR',
   'MESITI CLAUDIO',
   'MILAN ORDOQUI JAVIER',
   'VALDEZ MILTOS ROMINA',
   'GARCIA PABLO DANIEL',
   'PIÑEIRO CARINA',
   'PRUBNER CYNTHIA',
   'TRANI CLAUDIA',
   'CRISOFOLI PABLO',
   'URBANEJA, ESTER',
   'FAIRCHILD JORGE',
   'GIACUSA MARIA ALEJANDRA',
   'SINARDI MARCELO',
   'GARCIA STELLA'],
  'SUPERVISOR': ['PATANE ALICIA',
   'ZOCCALI JOSE LUIS',
   'ALFARO NADIA',
   'CAPUTO ROMINA',
   'ALVAREZ MARTIN',
   'BREPPE MARISA',
   'MARTINEZ MARIANA',
   'BOTANA ANTONIO',
   'PEREZ PATRICIA',
   'SOLODUJIN VANINA',
   'FERNANDEZ JUAN',
   'GONIONDZKY SILVINA',
   'BEITONE VANESA',
   'RIVERO CLAUDIA',
   'POLICANO ANTONIO',
   'FIORENZA GUSTAVO',
   'GONZALEZ CLAUDIA',
   'ATANIYA DIEGO',
   'CISNERO DIEGO',
   'BARBAGELATA RODOLFO',
   'PINTO JORGE',
   'MARTIN CAROLINA',
   'PETRELLA ANTONIO',
   'ALVAREZ PABLO',
   'CARLOS SOUTO',
   'ABELARDO ROMINA',
   'POSE LUCIANA',
   'SANTORA ALEJANDRO',
   'MILMAN MARIANO',
   'EDREIRA NORMA',
   'TRICOTTI GABRIELA',
   'AIELLO EDUARDO',
   'LENGARD CRISTINA',
   'GUMUCIO HUMBERTO',
   'LEGUIZAMON EMANUEL',
   'GONZALEZ MAURO',
   nan,
   'DOMINGUEZ JAVIER',
   'ARAMBURU GERMAN',
   'SPERONI MARCELO',
   'BALZANO CARLOS',
   "D'APICE ADRIANA",
   'RUBIO MARCELO',
   'CEREZO MARCELA',
   'SALLES, ENRIQUE',
   'ZELVYS SERGIO',
   'LASPINA ROXANA',
   'MANCHINI HERNAN',
   'ANTONELLI MARTA',
   'CAPARRA MARCELA',
   'ARFUSO VIVIANA',
   'GARCIA STELLA MARIS',
   "D'AMICO VANINA",
   'CEPURBEDA JORGE',
   'BIANCHI MARIA FERNANDA',
   'GIAMMARCHE DANIEL',
   'MONTERO FERNANDO',
   'COHEN, LEONOR',
   'SANCHEZ ARIAS HILDA',
   'GARIB JOSE LUIS',
   'BECERRA PEREZ HUGO',
   'MERA ANDREA',
   'COLUCCIO JORGE',
   'MELILLO MARCELO',
   'JULIAN YAMIL',
   'ALVAREZ DANIEL'],
  'CUIT': ['30710240244',
   '33707083129',
   '30529994393',
   '30708826568',
   '30708449853',
   '30647312523',
   '30707713212',
   '30687722007',
   '30612677499',
   '30539749435',
   '30702276957',
   '20127020303',
   '30709788880',
   '30500846301',
   '30646489675',
   '20937426446',
   '30708938935',
   '30712349626',
   '30708628227',
   '30643475673',
   '30712255036',
   '30691152177',
   '30501887214',
   '27003824484',
   '30504996588',
   '30709490644',
   '30711212856',
   '30711902836',
   '20041222795',
   '30708088575',
   '30685140221',
   '30711810931',
   '30710183437',
   '30708424559',
   '30709030597',
   '30709187941',
   '30709452408',
   '30711958076',
   '30708422300',
   '30707786279',
   '30709008044',
   '30708810777',
   '30592724541',
   '30708557346',
   '30681490465',
   '30714059730',
   '30677297322',
   '30709565075',
   '27138572574',
   '27382545880',
   '30709835420',
   '30570135585',
   '30551667800',
   '30502574945',
   '30709053988',
   '33500057039',
   '30710104154',
   '30711018405',
   '30648812856',
   '30711274355',
   '30711573999',
   '30708585447',
   '20936968407',
   '30711494123',
   '30710616155',
   '20078874326',
   '30.709.710.237',
   '30709568376',
   '30646710207',
   '30500037217',
   '30712273743',
   '30709325120',
   '30527677331',
   '30711054002',
   '30712156674',
   '30541138249',
   '30604801105',
   '30692324605',
   '20130229787',
   '30710263015',
   '20131315067',
   '30659867504',
   '30684968528',
   '30690995170',
   '30574816870',
   '30609645977',
   '30707813543',
   '30711259534',
   '30696041640',
   '30710935196',
   '33710301919',
   '30656171827',
   '30657107758',
   '30549547288',
   '30500051309',
   '30713110406',
   '20329194990',
   '33578969409',
   '20076564257',
   '30710488327',
   '30707681019',
   '20043176391',
   '30709051659',
   '30502793175',
   '30610252334',
   '30710852916',
   '30642025615',
   '30537131000',
   '30708143762',
   '30685793136',
   '30708434686',
   '30693290925',
   '30710640285',
   '30609788352',
   '30500050795',
   '33707830889',
   '30709264482',
   '30712549838',
   '20263598157',
   '30679732532',
   '30653484778',
   '30710443471',
   '30676613303',
   '30707279547',
   '30632464904',
   '27222406892',
   '30500064478',
   '30711227675',
   '30699408154',
   '30518919349',
   '30707385525',
   '30601002651',
   '30687471349',
   '30710689640',
   '33645022659',
   '30533285119',
   '33547992429',
   '30500045406',
   '30507066824',
   '30678184779',
   '30695108520',
   '30690973517',
   '30707813780',
   '33573855839',
   '30646279174',
   '30708515791',
   '30710821204',
   '30709228494',
   '30685781502',
   '30711352844',
   '30708643331',
   '30500143297',
   '30707946144',
   '30712203273',
   '30710180004',
   '30504913712',
   '30694747546',
   '33708555709',
   '30652248582',
   '30612032846',
   '30710969244',
   '30709439754',
   '30659932640',
   '27145584162',
   '20266320915',
   '30690785052',
   '30500772324',
   '27255257701',
   '30550119745',
   '30711355371',
   '30709425389',
   '30521092501',
   '20176356139',
   '30500010602',
   '30671375900',
   '30500010912',
   '30500012516',
   '30671859339',
   '30500009442',
   '30500098801',
   '33686664649',
   '30704960995',
   '30500012443',
   '30518954241',
   '30522714417',
   '30580189411',
   '30500010084',
   '30500006613',
   '30569151763',
   '33500005179',
   '30500005179',
   '30546741636',
   '23928913244',
   '27000522738',
   '27025029157',
   '23946043664',
   '20180946641',
   '20219541660',
   '30708946563',
   '20164920144',
   '30711109850',
   '30695558208',
   '20352298108',
   '30691323958',
   '20134804212',
   '30500064230',
   '30714092517',
   '30999228565',
   '30711770441',
   '30677428402',
   '30678172762',
   '30710016255',
   '20145633851',
   '30568222187',
   '20163771064',
   '30708112824',
   '20045521215',
   '30500035788',
   '30685893076',
   '30711043140',
   '30500678042',
   '30711304173',
   '30662982837',
   '30708568240',
   '30693503953',
   '30693504186',
   '30696159609',
   '30710844131',
   '30711878633',
   '30663391026',
   '30678158506',
   '20131325062',
   '30709560650',
   '30694376432',
   '30707498338',
   '30649364040',
   '30709925322',
   '30692311392',
   '30711853959',
   '30709334685',
   '23933685799',
   '30710523521',
   '30690207423',
   '30574893395',
   '30707044299',
   '30582170653',
   '30537486410',
   '30566275232',
   '30710859317',
   '30714367540',
   '27176122000',
   '30500001115',
   '30525586878',
   '33710499409',
   '30690196634',
   '20183791924',
   '30708239972',
   '30500034552',
   '30710811160',
   '27039768297',
   '30519882767',
   '30708440546',
   '30708206624',
   '30687288145',
   '30711635366',
   '20105505494',
   '20112256025',
   '30599017433',
   '30710219865',
   '20120864425',
   '30582202253',
   '30647218489',
   '30707735607',
   '30709779164',
   '30680718268',
   '30680748876',
   '30594336247',
   '30707879234',
   '30707264951',
   '30708656832',
   '30708834560',
   '20045420370',
   '30705644310',
   '30537341811',
   '30711981531',
   '30710983107',
   '30707732055',
   '30707419497',
   '20245642033',
   '30663205621',
   '30500039678',
   '30709210293',
   '30707979050',
   '20169730785',
   '30551291290',
   '20288034843',
   '23238660939',
   '30657864281',
   '20172327576',
   '30708621761',
   '30621500917',
   '20102017871',
   '20225487018',
   '27120860459',
   '30698744177',
   '30708983906',
   '30615911654',
   '30640324097',
   '20139773889',
   '20940987947',
   '30693215311',
   '30677558268',
   '30711416508',
   '20166808201',
   '30711125155',
   '30711966052',
   '30708130865',
   '20234632338',
   '30584620389',
   '23200093119',
   '30550095714',
   '30526008835',
   '30538058743',
   '30678264659',
   '30577466102',
   '23938772304',
   '20231549804',
   '20043043162',
   '20226532537',
   '20182988503',
   '27208324182',
   '20127025968',
   '30709492922',
   '30712028382',
   '20042953874',
   '30636345454',
   '27930868472',
   '30658963895',
   '30501111747',
   '30646451422',
   '30709272914',
   '30710164637',
   '30590360763',
   '30708167300',
   '30707813519',
   '30546128403',
   '30658804657',
   '30652543630',
   '30708927763',
   '30712411364',
   '30709460532',
   '30575054354',
   '23124548799',
   '30652834317',
   '20044148723',
   '33508358259',
   '30623347296',
   '20231015117',
   '30708927690',
   '33624100439',
   '27940288024',
   '27939377048',
   '27247530229',
   '20042235068',
   '30523479241',
   '30708290447',
   '27321880776',
   '30710791550',
   '20928915025',
   '27928720425',
   '30708602619',
   '23043163019',
   '30685158341',
   '30709858773',
   '30500032266',
   '30708420189',
   '30708044985',
   '30695305644',
   '30708617632',
   '30500036911',
   '30689011051',
   '20291355936',
   '27214740422',
   '30636741120',
   '30709787442',
   '30517675292',
   '30557107416',
   '30708135433',
   '30709390682',
   '30500005625',
   '30709247820',
   '30710659717',
   '30707176284',
   '20102333951',
   '30708709227',
   '30504912899',
   '27045518472',
   '30654181744',
   '30658422762',
   '30628436238',
   '30708327472',
   '30711479399',
   '30711448442',
   '33707725929',
   '30682408622',
   '30552483304',
   '30711070725',
   '30525390086',
   '30664021435',
   '30599942226',
   '30709550949',
   '27248821499',
   '33711009359',
   '30708743476',
   '30520760535',
   '30561625960',
   '30691618389',
   '33711696259',
   '30568642186',
   '30696899459',
   '30707021426',
   '30711656231',
   '30711322236',
   '30709876984',
   '30709193984',
   '30697250367',
   '30710739729',
   '30649229755',
   '30710345364',
   '30506733932',
   '30626221811',
   '30708376740',
   '30652012465',
   '30708403195',
   '30709063800',
   '30581570313',
   '30707735127',
   '30708908378',
   '30710831978',
   '30655037248',
   '30709418659',
   '30708239824',
   '30708886595',
   '33710114299',
   '30712860509',
   '30546694646',
   '30633369220',
   '30711641641',
   '33710018079',
   '30710593570',
   '30705451040',
   '30708389168',
   '30708676906',
   '30566207377',
   '30710634447',
   '30710236050',
   '30710422946',
   '33711952549',
   '30633390688',
   '30590745797',
   '30561788096',
   '30661957065',
   '30707804617',
   '30708190426',
   '30518965715',
   '30662934174',
   '30709615846',
   '30709982350',
   '30708447494',
   '30624185044',
   '30673380162',
   '27056657695',
   '30708204907',
   '30650156109',
   '20240833914',
   '30711097674',
   '30632560717',
   '30709764809',
   '33709416869',
   '30709479624',
   '20082088963',
   '30713060506',
   '30711007047',
   '30710277334',
   '30567998130',
   '30712231250',
   '30711406995',
   '30707937382',
   '30707201882',
   '30624349004',
   '30697986126',
   '30682503994',
   '27162229430',
   '30708494107',
   '20045845177',
   '30503517767',
   '30709207209',
   '30588223775',
   '30622216309',
   '30710957157',
   '30710779062',
   '30509300700',
   '30589398951',
   '27104634120',
   '30711854629',
   '30701019268',
   '30615474653',
   '20942768185',
   '30712332006',
   '30708706791',
   '30702033639',
   '33709828369',
   '30708201657',
   '30711274223',
   '23177555789',
   '30559161949',
   '30711531293',
   '30710663072',
   '30708671491',
   '30709240567',
   '33695610659',
   '30640766030',
   '33709116539',
   '30677757814',
   '30710777086',
   '20367283085',
   '20345343793',
   '30708368772',
   '30709274674',
   '30711658684',
   '30553566602',
   '20160501104',
   '20211398915',
   '30684734799',
   '20231025686',
   '30710855206',
   '30708065508',
   '30601951394',
   '30596116201',
   '30712455906',
   '20223623191',
   '30710721102',
   '20290381852',
   '20280306011',
   '30500876391',
   '20085864905',
   '30712488065',
   '30707874259',
   '30607462905',
   '33663184739',
   '30711460051',
   '27923427886',
   '30598083890',
   '20233291065',
   '33684058679',
   '30655189730',
   '20126017856',
   '30707463178',
   '33629282659',
   '20186513437',
   '27172947714',
   '30685146335',
   '30632345476',
   '20044152607',
   '30701307115',
   '20041707292',
   '30707397760',
   '30707921214',
   '30580111315',
   '20042338002',
   '30685849751',
   '30708741163',
   '20111687413',
   '20162463315',
   '30551518694',
   '30693283724',
   '20221476213',
   '30710685033',
   '30708253010',
   '30707830960',
   '30596118352',
   '27948025294',
   '30546696968',
   '30685889397',
   '30710597651',
   '33711113539',
   '30711268215',
   '30696731825',
   '33708522819',
   '33642616949',
   '33709496919',
   '33657865279',
   '30708879017',
   '30708935650',
   '33709418489',
   '30686869098',
   '30709014184',
   '30712063900',
   '33708255349',
   '20077309403',
   '30708112727',
   '30711309086',
   '20134654091',
   '27259874160',
   '30636021578',
   '30707439587',
   '30606801765',

### Verificaciion ortografia española de los valores

In [6]:
# Para analizar la ortografía en español de las columnas se puede usar la siguiente función e instalar la librería fuzzywuzzy

import sys
print(sys.path)


import re
from fuzzywuzzy import fuzz


def ortografia_columnas(df):
    columnas = df.columns
    columnas = [re.sub(r'[^a-zA-Z0-9 ]', '', columna) for columna in columnas]
    columnas = [columna.lower() for columna in columnas]
    columnas = [columna.replace(' ', '') for columna in columnas]
    columnas = [columna for columna in columnas if columna != '']
    columnas = list(set(columnas))
    ortografia = []
    for columna in columnas:
        if fuzz.ratio(columna, 'año') < 90:
            ortografia.append(columna)
    return ortografia

print("-------------------------")  
print("Ortografía de las columnas")
print("-------------------------")  
print(ortografia_columnas(df))

['c:\\Users\\20927322707\\Desktop\\analizador_datasets\\Analizador', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\python312.zip', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\DLLs', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3', '', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages\\win32', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages\\win32\\lib', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages\\Pythonwin', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages\\setuptools\\_vendor']

ModuleNotFoundError: No module named 'fuzzywuzzy'

In [3]:
# Se crea un objeto de la clase CalidadDatos con los datos de interés
ruta_covid = "dataset ejemplos.xlsx"
datos_covid = CalidadDatos(ruta_covid)

C:\Users\jairoruiz\Documents\GitHub\leila_env\lib\site-packages\leila\calidad_datos.py:1307: UserWarning: Cargar archivos xlsx puede tomar demasiado tiempo, se aconseja fuertemente convertirlos a archivo csv, esto puede mejorar hasta 100x veces la velocidad de carga del archivo dataset ejemplos.xlsx
  "Cargar archivos xlsx puede tomar demasiado tiempo, se aconseja "

#### 1. Tabla de resumen
El método "resumen" calcula varias estadísticas que dan una primera impresión del conjunto de datos. 

Estas métricas incluyen el número de filas y columnas; número de columnas de distintos tipos; número de filas y columnas repetidas (duplicadas); columnas con muchos datos faltantes o extremos; peso del conjunto de datos

#### 2. Tipos de cada columna
El método "TipoColumnas" calcula el tipo de cada columna de tres maneras diferentes. 

La primera es el tipo general de la columna en español. Indica si el tipo es numérico, texto, fecha, booleano u otro

La segunda muestra el tipo general según el método dtypes de Python.

La tercera manera muestra los tipos de cada celda de cada columna. Es decir, muestra la distribución de tipos de cada columna. El tipo que más aparece en esa columna se muestra en la variable "tipo_especifico_1" de la tabla de tipos y muestra el porcentaje. En caso de haber más de un tipo, se mostrará en las siguientes columnas "tipo_especifico_#"

El ejemplo abajo muestra cómo el es código para generar los resultados de los tipos con el método "TipoCOlumnas". Los parámetros del método especifican qué tipo se quiere mostrar para las columnas (con las opciones True o False)

In [5]:
tipos = datos_covid.TipoColumnas(tipoGeneral=True, 
                                 tipoGeneralPython=True, 
                                 tipoEspecifico=True)
tipos

,tipo_general,tipo_general_python,tipo_especifico_1,tipo_especifico_2
ID de caso,Texto,string,'str': 100.0%,
Fecha de notificación,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 10...,
Código DIVIPOLA,Texto,string,'str': 100.0%,
Ciudad de ubicación,Texto,string,'str': 100.0%,
Departamento o Distrito,Texto,string,'str': 100.0%,
Atención,Texto,string,'str': 99.71%,'pandas._libs.missing.NAType': 0.29%
Edad,Numérico,Int64,'int': 100.0%,
Edad 2,Numérico,Int64,'int': 100.0%,
Edad meses,Numérico,Int64,'int': 100.0%,
Sexo,Texto,string,'str': 100.0%,
Tipo,Texto,string,'str': 100.0%,
Estado,Texto,string,'str': 99.66%,'pandas._libs.missing.NAType': 0.34%
País de procedencia,Texto,string,'pandas._libs.missing.NAType': 98.58%,'str': 1.42%
Fecha de inicio de síntomas,Texto,string,'str': 100.0%,
Fecha de muerte,Fecha,datetime64[ns],'pandas._libs.tslibs.nattype.NaTType': 95.38%,'pandas._libs.tslibs.timestamps.Timestamp': 4.62%
Fecha diagnostico,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 98...,'pandas._libs.tslibs.nattype.NaTType': 1.59%
Fecha recuperado,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 91...,'pandas._libs.tslibs.nattype.NaTType': 8.67%
Fecha reporte web,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 10...,
Fecha de registro,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 10...,
Tipo recuperación,Texto,string,'str': 91.33%,'pandas._libs.missing.NAType': 8.67%
Codigo departamento,Texto,string,'str': 100.0%,
Codigo pais,Texto,string,'pandas._libs.missing.NAType': 98.65%,'str': 1.35%
Pertenencia etnica,Texto,string,'str': 98.13%,'pandas._libs.missing.NAType': 1.87%
Nombre grupo etnico,Texto,string,'pandas._libs.missing.NAType': 97.97%,'str': 2.03%
Diccionario,Texto,string,'str': 100.0%,

#### 3. Datos faltantes

El método "ValoresFaltantes" permite calcular el número o porcentaje de valores faltantes de un conjunto de datos. Si el parámetro "numero" tiene asignado el valor True, se calcula el número de valores faltantes de cada columna. De lo contrario, si es False, se calcula el porcentaje.

El ejemplo a continuación presenta los porcentajes de datos faltantes de cada columna del conjunto de datos de COVID-19

In [6]:
faltantes = datos_covid.ValoresFaltantes(numero = False)
faltantes

ID de caso                     0.000000
Fecha de notificación          0.000000
Código DIVIPOLA                0.000000
Ciudad de ubicación            0.000000
Departamento o Distrito        0.000000
Atención                       0.002941
Edad                           0.000000
Edad 2                         0.000000
Edad meses                     0.000000
Sexo                           0.000000
Tipo                           0.000000
Estado                         0.003414
País de procedencia            0.985766
Fecha de inicio de síntomas    0.000000
Fecha de muerte                0.953837
Fecha diagnostico              0.015941
Fecha recuperado               0.086701
Fecha reporte web              0.000000
Fecha de registro              0.000000
Tipo recuperación              0.086701
Codigo departamento            0.000000
Codigo pais                    0.986512
Pertenencia etnica             0.018745
Nombre grupo etnico            0.979685
Diccionario                    0.000000
dtype: float64

#### 4. Datos duplicados

El método "CantidadDuplicados" calcula el número o porcentaje de duplicados en el conjunto de datos. 

El ejemplo abajo calcula el número de duplicados para filas y columnas del conjunto de datos de COVID-19.

In [7]:
# Número de filas duplicadas. 
# Se escribe el parámetro eje = 0, para especificar fila
# Se escribe el parámetro numero = True, para especificar el número de duplicados (si es False se calcula el porcentaje)
filas_duplicadas = datos_covid.CantidadDuplicados(eje = 0, numero = True)

# Número de columnas duplicadas. 
# Se escribe el parámetro eje = 1, para especificar columna
# Se escribe el parámetro numero = False, para especificar el porcentaje de duplicados
columnas_duplicadas = datos_covid.CantidadDuplicados(eje = 1, numero = True)

print("Filas duplicadas: ", filas_duplicadas)
print("Columnas duplicadas: ", columnas_duplicadas)

Filas duplicadas:  1
Columnas duplicadas:  2

#### 5. Emparejamiento de duplicados
El método "EmparejamientoDuplicados" permite mostrar los nombres de filas o columnas que son exactamente iguales. El parámetro "col" especifica si se quieren emparejar los duplicados de filas al asignarlo a False. Para emparejar las columnas se escribe True.

EL ejemplo abajo muestra los nombres de las filas duplicadas en cada columna de la tabla. Por ejemplo, la columna de la tabla "Filas iguales 1" muestra que las filas 1 y 2 son duplicadas.

In [8]:
emparejamiento_dupli_filas = datos_covid.EmparejamientoDuplicados(col = False)
emparejamiento_dupli_filas

   Filas iguales 1
0              267
1              269

EL ejemplo abajo muestra los nombres de las columnas duplicadas en cada columna de la tabla. Por ejemplo, la columna de la tabla "Columnas iguales 1" muestra que las columnas "Edad" y "Edad 2" son duplicadas

In [9]:
emparejamiento_dupli_cols = datos_covid.EmparejamientoDuplicados(col = True)
emparejamiento_dupli_cols

  Columnas iguales 1 Columnas iguales 2
0               Edad  Fecha reporte web
1             Edad 2  Fecha de registro

#### 6. Estadísticas descriptivas de variables numéricas

El método DescripcionNumericas permite calcular estadísticas descriptivas para variables numéricas tales como el promedio, la desviación estándar, el mínimo, máximo, mediana (percentil 50), valores faltantes y extremos. 

El objetivo de estos cálculos es verificar si las variables del conjunto de datos contienen los valores esperados o si existen errores en la digitación de los valores

El ejemplo abajo muestra las estadísticas descriptivas para las variables "Edad", "Edad_2" y "Edad meses"

In [10]:
descr_numericas = datos_covid.DescripcionNumericas()
descr_numericas

,count,mean,std,min,25%,50%,75%,max,missing,outliers_total,outliers_altos,outliers_bajos
Edad,65616.0,39.175536,18.661339,0.0,26.0,36.0,52.0,104.0,0.0,0.002865,0.002865,0.0
Edad 2,65616.0,39.175536,18.661339,0.0,26.0,36.0,52.0,104.0,0.0,0.002865,0.002865,0.0
Edad meses,65616.0,476.099625,223.962309,1.0,318.0,443.0,626.0,1250.0,0.0,0.004054,0.004054,0.0

Es posible calcular las estadísticas descriptivas para algunas variables únicamente. Esto se hace al asignar una lista con las variables de interés al parámetro "variales", como se muestra a continuación

In [11]:
descr_numericas = datos_covid.DescripcionNumericas(variables = ["Edad", "Edad meses"])
descr_numericas

,count,mean,std,min,25%,50%,75%,max,missing,outliers_total,outliers_altos,outliers_bajos
Edad,65616.0,39.175536,18.661339,0.0,26.0,36.0,52.0,104.0,0.0,0.002865,0.002865,0.0
Edad meses,65616.0,476.099625,223.962309,1.0,318.0,443.0,626.0,1250.0,0.0,0.004054,0.004054,0.0

#### 7. Estadísticas descriptivas de variables categóricas
El método DescripcionCategoricas calcula la frecuencia, tanto en número como en porcentaje del total de filas, de los valores de las variables que se consideran numéricas. 

Las variables se consideran categóricas si contienen valores limitados. Por defecto, el máximo número de categorías es 30 y las categorías no pueden representar más del 50% del total de filas de la columna. Estos valores se pueden modificar en los parámetros "limite" y "categoriasMaximas" del método "DescripcionCategoricas". 

Es posible también especificar si las variables numéricas con pocos valores se quieren incluir en el análisis. Por ejemplo, variables que contienen únicamente los números 1 y 2. Para agregar las variables al análisis, se asigna el valor True al parámetro incluirNumericas (el cual está por defecto) y False si no se desean incluir.

Por último, es posible agregar una lista limitada de variables al análisis, asignando una lista de Python con las variables al parámetro "variables"

El ejemplo abajo muestra cómo se calculan las frecuencias de categorías de variables categóricas con los parámetros del método DescripcionCategoricas por defecto

In [12]:
descr_categoricas = datos_covid.DescripcionCategoricas(limite=0.5, 
                                                       categoriasMaximas=30, 
                                                       incluirNumericos=True, 
                                                       variables=None)
descr_categoricas

,Columna,Valor,Frecuencia,Porcentaje del total de filas
0,Atención,Recuperado,59927.0,0.913299
1,Atención,Fallecido,2914.0,0.044410
2,Atención,Hospital,2138.0,0.032584
3,Atención,Hospital UCI,438.0,0.006675
4,Atención,Casa,6.0,0.000091
5,Atención,Datos faltantes,193.0,0.002941
6,Atención,Total categorías (incluye NA): 6,NaN,NaN
0,Sexo,M,35552.0,0.541819
1,Sexo,F,30056.0,0.458059
2,Sexo,f,6.0,0.000091
3,Sexo,m,2.0,0.000030
4,Sexo,Datos faltantes,0.0,0.000000
5,Sexo,Total categorías (incluye NA): 4,NaN,NaN
0,Tipo,En estudio,50836.0,0.774750
1,Tipo,Relacionado,13847.0,0.211031
2,Tipo,Importado,933.0,0.014219
3,Tipo,Datos faltantes,0.0,0.000000
4,Tipo,Total categorías (incluye NA): 3,NaN,NaN
0,Estado,Leve,52084.0,0.793770
1,Estado,Asintomático,6811.0,0.103801
2,Estado,Moderado,3135.0,0.047778
3,Estado,Fallecido,2914.0,0.044410
4,Estado,Grave,448.0,0.006828
5,Estado,Datos faltantes,224.0,0.003414
6,Estado,Total categorías (incluye NA): 6,NaN,NaN
0,Tipo recuperación,PCR,35370.0,0.539045
1,Tipo recuperación,Tiempo,24557.0,0.374253
2,Tipo recuperación,Datos faltantes,5689.0,0.086701
3,Tipo recuperación,Total categorías (incluye NA): 3,NaN,NaN
0,Pertenencia etnica,Otro,57670.0,0.878901
1,Pertenencia etnica,Negro,5003.0,0.076247
2,Pertenencia etnica,Indígena,1333.0,0.020315
3,Pertenencia etnica,Rom,293.0,0.004465
4,Pertenencia etnica,Raizal,72.0,0.001097
5,Pertenencia etnica,Palenquero,15.0,0.000229
6,Pertenencia etnica,Datos faltantes,1230.0,0.018745
7,Pertenencia etnica,Total categorías (incluye NA): 7,NaN,NaN
0,Diccionario,{1},32808.0,0.500000
1,Diccionario,{2},32808.0,0.500000
2,Diccionario,Datos faltantes,0.0,0.000000
3,Diccionario,Total categorías (incluye NA): 2,NaN,NaN

#### 8. Peso de las variables en la memoria RAM
Para calcular cuál es el peso de cada variable, se utiliza el método "Memoria", como se muestra en el ejemplo abajo. El parámetro "unidad" indica que se quiere calcular en Mega Bytes ("Mb") y el parámetro "col" indica que se calcula para cada variable. En caso de desear calcular el peso total del conjunto de datos, se asigna False al parámetro "col".

In [13]:
peso_memoria = datos_covid.Memoria(col=True, unidad="Mb")
peso_memoria

Index                          0.000122
ID de caso                     0.500610
Fecha de notificación          0.500610
Código DIVIPOLA                0.500610
Ciudad de ubicación            0.500610
Departamento o Distrito        0.500610
Atención                       0.500610
Edad                           0.563187
Edad 2                         0.563187
Edad meses                     0.563187
Sexo                           0.500610
Tipo                           0.500610
Estado                         0.500610
País de procedencia            0.500610
Fecha de inicio de síntomas    0.500610
Fecha de muerte                0.500610
Fecha diagnostico              0.500610
Fecha recuperado               0.500610
Fecha reporte web              0.500610
Fecha de registro              0.500610
Tipo recuperación              0.500610
Codigo departamento            0.500610
Codigo pais                    0.500610
Pertenencia etnica             0.500610
Nombre grupo etnico            0.500610
Diccionario                    0.500610
dtype: float64

#### 9 Correlación entre variables numéricas

El método "CorrelacionNumericas" calcula una matriz de correlación entre las variables numéricas del conjunto de datos.

El parámetro "metodo" especifica si se desea calcular las correlaciones con el método Pearson ("pearson"), Kendall ("kendall") o Spearman ("spearman")

El ejemplo abajo muestra la matriz de correlación para variables numéricas del conjunto de datos de COVID-19

In [14]:
corr_numericas = datos_covid.CorrelacionNumericas(metodo="pearson", variables=None)
corr_numericas

              Edad  Edad 2  Edad meses
Edad        1.0000  1.0000      0.9999
Edad 2      1.0000  1.0000      0.9999
Edad meses  0.9999  0.9999      1.0000

#### 10. Correlación de variables categóricas
El método "CorrelacionCategoricas" calcula una matriz de correlación para variables categóricas. Contiene los mismos parámetros que se explicaron en la Sección 7, para definir variables categóricas, pero incluye también el parámetro "metodo". Este especifica si se quiere calcular la matriz con el método Cramer ("cramer") o con la metodología Phik ("phik"), de la librería Phik de Python.

A continuación se calcula la matriz de correlación de variables categóricas para el conjunto de datos de COVID-19

In [15]:
corr_categoricas = datos_covid.CorrelacionCategoricas(metodo="phik")
corr_categoricas

,Atención,Sexo,Tipo,Estado,Tipo recuperación,Pertenencia etnica,Diccionario
Atención,1.000000,0.038193,0.195794,0.987038,0.941437,0.028540,0.000000
Sexo,0.038193,1.000000,0.094794,0.041878,0.025933,0.000000,0.000000
Tipo,0.195794,0.094794,1.000000,0.325888,0.320547,0.133658,0.000000
Estado,0.987038,0.041878,0.325888,1.000000,0.917328,0.067380,0.004040
Tipo recuperación,0.941437,0.025933,0.320547,0.917328,1.000000,0.051298,0.000000
Pertenencia etnica,0.028540,0.000000,0.133658,0.067380,0.051298,1.000000,0.002036
Diccionario,0.000000,0.000000,0.000000,0.004040,0.000000,0.002036,1.000000