# Módulo calidad_datos - LEILA
Este libro de Jupyter contiene ejemplos con explicaciones de cómo utilizar el módulo que presenta métricas de calidad y descriptivas para conjuntos de datos estructurados

In [2]:
# Se importar la clase CalidadDatos del módulo calidad_datos

import pandas as pd
import numpy as np

#### Se importan los csvs

In [3]:
# se importan los csvs

df = pd.read_csv('C:\\Users\\20927322707\\Desktop\\analizador_datasets\\csv\\actuaciones-fiscalizacion\\historial-de-contribuyentes-bajo-inspeccion.csv', sep=',', encoding='utf-8')

In [4]:
# se visualizan las principales características del dataset , como su metadata y la completitud y calidad de los datos

print("-------------------------")
print("Infomración principal del dataset")
print("-------------------------")
print(df.info())

# calcular la completitud de los datos

completitud_df = df.count() / len(df) * 100
completitud_df = completitud_df.sort_values(ascending=False)

print("-------------------------")
print("Completitud de los datos")
print("-------------------------")
print(completitud_df)

print("-------------------------")
print("Estas son las dimensiones del dataset")
print("-------------------------")
print("Filas: {}".format(df.shape[0]))
print("Columnas: {}".format(df.shape[1]))
print("-------------------------")
# print("Estas son las estadisticas del dataset")
# print(df.describe())
print("-------------------------")
print("Primeras 5 filas del dataset")
print("-------------------------")
print(df.head(5))
print("-------------------------")
print("Estas son las filas duplicadas del dataset")
print("-------------------------")
print(df.duplicated().sum())    
print("-------------------------")
print("Valores unicos")
print("-------------------------")
print(df.nunique())
print("-------------------------")  
print("Valores nulos")    
print("-------------------------")
print(df.isna().sum())
print("-------------------------")
print("Tipos de datos")
print("-------------------------")
print(df.dtypes)


if df.select_dtypes(include=['object']).shape[1] > 0:
    print("El dataset contiene variables categóricas")
    print("-------------------------") 
    print("Variables categóricas")
    print("-------------------------")
    print(df.select_dtypes(include=['object']).columns)
    print("-------------------------")
    print("Valores únicos de las variables categóricas")
    print("-------------------------")
    print(df.select_dtypes(include=['object']).nunique())

else:
    print("El dataset no contiene variables categóricas")


valores_unicos_categoricos =  df.select_dtypes(include=['object']).nunique()

print("-------------------------")
print("Valores únicos de las variables categóricas")
print("-------------------------")
print(valores_unicos_categoricos)

-------------------------
Infomración principal del dataset
-------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12356 entries, 0 to 12355
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PERIODO            12356 non-null  object
 1   NUM_ORDEN          12356 non-null  int64
 2   DEPARTAMENTO       12356 non-null  object
 3   DIVISION           11238 non-null  object
 4   INSPECTOR          12356 non-null  object
 5   SUPERVISOR         12290 non-null  object
 6   CUIT               12350 non-null  float64
 7   RAZON_SOCIAL       12356 non-null  object
 8   FECHA_INICIO       12270 non-null  object
 9   FECHA_DEVOL_TRANS  1899 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 965.4+ KB
None
-------------------------
Completitud de los datos
-------------------------
PERIODO              100.000000
NUM_ORDEN            100.000000
DEPARTAMENTO         100.000000
INSPECTOR            100.000000
RAZON_SOCIAL         100.000000
CUIT                  99.951441
SUPERVISOR            99.465847
FECHA_INICIO          99.303982
DIVISION              90.951764
FECHA_DEVOL_TRANS     15.369051
dtype: float64
-------------------------
Estas son las dimensiones del dataset
-------------------------
Filas: 12356
Columnas: 10
-------------------------
-------------------------
Primeras 5 filas del dataset
-------------------------
       PERIODO  NUM_ORDEN DEPARTAMENTO DIVISION         INSPECTOR  \
0  1 TRIM 2014          1    EXTERNA E       II  TRACCHIA EDUARDO
1  1 TRIM 2015          1    EXTERNA E        I      CRESPO ARIEL
2  2 TRIM 2015          1    EXTERNA E        I      CRESPO ARIEL
3  3 TRIM 2014          1    EXTERNA E        I      CRESPO ARIEL
4  3 TRIM 2015          1    EXTERNA E        I      CRESPO ARIEL

       SUPERVISOR          CUIT    RAZON_SOCIAL FECHA_INICIO FECHA_DEVOL_TRANS
0  ARFUSO VIVIANA  3.369613e+10  07 B A TEX SRL   29/04/2013               NaN
1   PATANE ALICIA  3.071024e+10  1001 FARDO SRL   23/09/2014               NaN
2   PATANE ALICIA  3.071024e+10  1001 FARDO SRL   23/09/2014               NaN
3   PATANE ALICIA  3.071024e+10  1001 FARDO SRL   23/09/2014               NaN
4   PATANE ALICIA  3.071024e+10  1001 FARDO SRL   01/10/2014               NaN
-------------------------
Estas son las filas duplicadas del dataset
-------------------------
0
-------------------------
Valores unicos
-------------------------
PERIODO                 7
NUM_ORDEN            1945
DEPARTAMENTO           16
DIVISION               21
INSPECTOR             395
SUPERVISOR             78
CUIT                 4147
RAZON_SOCIAL         4518
FECHA_INICIO          889
FECHA_DEVOL_TRANS     448
dtype: int64
-------------------------
Valores nulos
-------------------------
PERIODO                  0
NUM_ORDEN                0
DEPARTAMENTO             0
DIVISION              1118
INSPECTOR                0
SUPERVISOR              66
CUIT                     6
RAZON_SOCIAL             0
FECHA_INICIO            86
FECHA_DEVOL_TRANS    10457
dtype: int64
-------------------------
Tipos de datos
-------------------------
PERIODO               object
NUM_ORDEN              int64
DEPARTAMENTO          object
DIVISION              object
INSPECTOR             object
SUPERVISOR            object
CUIT                 float64
RAZON_SOCIAL          object
FECHA_INICIO          object
FECHA_DEVOL_TRANS     object
dtype: object
El dataset contiene variables categóricas
-------------------------
Variables categóricas
-------------------------
Index(['PERIODO', 'DEPARTAMENTO', 'DIVISION', 'INSPECTOR', 'SUPERVISOR',
       'RAZON_SOCIAL', 'FECHA_INICIO', 'FECHA_DEVOL_TRANS'],
      dtype='object')
-------------------------
Valores únicos de las variables categóricas
-------------------------
PERIODO                 7
DEPARTAMENTO           16
DIVISION               21
INSPECTOR             395
SUPERVISOR             78
RAZON_SOCIAL         4518
FECHA_INICIO          889
FECHA_DEVOL_TRANS     448
dtype: int64
-------------------------
Valores únicos de las variables categóricas
-------------------------
PERIODO                 7
DEPARTAMENTO           16
DIVISION               21
INSPECTOR             395
SUPERVISOR             78
RAZON_SOCIAL         4518
FECHA_INICIO          889
FECHA_DEVOL_TRANS     448
dtype: int64

In [5]:
import pandas as pd
import numpy as np 

# Obtener los valores únicos de las variables categóricas

# Seleccionar las variables categóricas

valores_categoricos = df.select_dtypes(include=['object'])  # Seleccionar las variables categóricas

print(valores_categoricos)

valores_categoricos = pd.DataFrame(valores_categoricos) # Convertir las variables categóricas en un DataFrame

valores_categoricos_dataframe = valores_categoricos.nunique()

print(valores_categoricos_dataframe)

           PERIODO DEPARTAMENTO DIVISION         INSPECTOR  \
0      1 TRIM 2014    EXTERNA E       II  TRACCHIA EDUARDO
1      1 TRIM 2015    EXTERNA E        I      CRESPO ARIEL
2      2 TRIM 2015    EXTERNA E        I      CRESPO ARIEL
3      3 TRIM 2014    EXTERNA E        I      CRESPO ARIEL
4      3 TRIM 2015    EXTERNA E        I      CRESPO ARIEL
...            ...          ...      ...               ...
12351  1 TRIM 2015    EXTERNA E        I     FIASCHE RUBEN
12352  3 TRIM 2014    EXTERNA E        I     FIASCHE RUBEN
12353  4 TRIM 2014    EXTERNA E        I     FIASCHE RUBEN
12354  1 TRIM 2014   OPERATIVOS        A    BIELAT EUGENIO
12355  1 TRIM 2015    EXTERNA A       II       OUTON JULIO

               SUPERVISOR            RAZON_SOCIAL FECHA_INICIO  \
0          ARFUSO VIVIANA          07 B A TEX SRL   29/04/2013
1           PATANE ALICIA          1001 FARDO SRL   23/09/2014
2           PATANE ALICIA          1001 FARDO SRL   23/09/2014
3           PATANE ALICIA          1001 FARDO SRL   23/09/2014
4           PATANE ALICIA          1001 FARDO SRL   01/10/2014
...                   ...                     ...          ...
12351       PATANE ALICIA  ZUMMER GRACIELA MONICA   21/10/2014
12352       PATANE ALICIA  ZUMMER GRACIELA MONICA   21/10/2014
12353       PATANE ALICIA  ZUMMER GRACIELA MONICA   21/10/2014
12354     MELILLO MARCELO                 ZUN SRL   12/05/2014
12355  LEGUIZAMON EMANUEL            ZURICH ARGEN          NaN

      FECHA_DEVOL_TRANS
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
12351               NaN
12352               NaN
12353               NaN
12354               NaN
12355               NaN

[12356 rows x 8 columns]
PERIODO                 7
DEPARTAMENTO           16
DIVISION               21
INSPECTOR             395
SUPERVISOR             78
RAZON_SOCIAL         4518
FECHA_INICIO          889
FECHA_DEVOL_TRANS     448
dtype: int64

In [8]:
import pandas as pd
import json

# Obtener los valores únicos de las variables categóricas exeptuando las columnas que refieran a fechas
 
valores_unicos_por_categoria = {
    "valores_unicos": {
        columna: df[columna].unique().tolist()
        for columna in df.select_dtypes(include=['object']).columns
        if 'fecha' not in columna.lower()  # Filtra columnas que no contengan la palabra "fecha"
    }
}

with open('valores_unicos_hist_contribuyentes.json', 'w') as f:      # Abrir un archivo JSON para guardar los valores únicos 'w' es para escribir with es para abrir y cerrar el archivo
    json.dump(valores_unicos_por_categoria, f, indent=4) # Guardar los valores únicos en un archivo JSON donde f es el archivo indent es la identación y dump es para guardar

valores_unicos_por_categoria

{'valores_unicos': {'PERIODO': ['1 TRIM 2014',
   '1 TRIM 2015',
   '2 TRIM 2015',
   '3 TRIM 2014',
   '3 TRIM 2015',
   '4 TRIM 2014',
   '2 TRIM 2014'],
  'DEPARTAMENTO': ['EXTERNA E',
   'EXTERNA D',
   'PUBLICIDAD REG SIMPL Y OPERATIVOS',
   'EXTERNA B',
   'EXTERNA A',
   'EXTERNA C',
   'CONCURSOS Y QUIEBRAS',
   'EXTERNA F',
   'OPERATIVOS',
   'NORMAS Y MANUALES DE FISCALIZACION',
   'PLANIFICACION Y SELECCION',
   'REVISION Y CONTROL DE FISCALIZACION',
   'PUBLICIDAD, REG SIMPL DEL ISIB Y  OPERATIVOS',
   'BANCOS',
   'PUBLICIDAD, REG SIMPL DEL ISIB Y OPERATIVOS',
   'DEPARTAMENTO PLANIFICACION Y SELECCION'],
  'DIVISION': ['II',
   'I',
   'SELLOS',
   'B',
   'V',
   'VI',
   'VII',
   'I0',
   nan,
   'III',
   'VIII',
   'A',
   'IV',
   'IX',
   'EQUIPO A',
   'INTERNA I',
   'E',
   'INTERNA II',
   'C',
   'D',
   'EQUIPO RELEVADORES',
   'BANCOS'],
  'INSPECTOR': ['TRACCHIA EDUARDO',
   'CRESPO ARIEL',
   'SILEO ANALIA',
   'CARDONE MARIANO',
   'LANFRANCO PABLO',
   'SICILIANO MARIA ROSA',
   'NALBANDIAN M. CRISTINA',
   'PERALTA MARCELA',
   'COMI MARIO JORGE',
   'BERNALDO DE QUIROS ALVARO',
   'CODERCH ROCHE TATIANA',
   'RUA CLAUDIA',
   'VALDES DAMIAN JAVIER',
   'FERNANDEZ VAQUERA, B',
   'ZAPATA  MARIA CECILIA',
   'PEDRO ROMINA',
   'IBARRA CARLOS',
   'ABUIN VERONICA',
   'ROJAS LORENA',
   'RIPOLI JORGE',
   'AGUERO MONICA',
   'BODNER ALEJANDRA',
   'ANDREU DANIEL',
   'LENAGHAN OSVALDO',
   'PEREZ MONICA',
   'CAPUTO CARLOS',
   'LOPEZ GUSTAVO',
   'ABBEDUTO JUAN JOSE',
   'NOVOA NANCY',
   'IGLESIAS LILIANA',
   'REIST MARTA PATRICIA',
   'MOYA JULIETA ANDREA',
   'RODRIGUEZ ROBERTO',
   'NOVOA MARIANA',
   'MALAGUEO, ELDA A.',
   'PEREIRA VIVIANA',
   'COHEN LEONOR ',
   'VEGA DANIEL',
   'DITURI ADRIANA',
   'MARI CRISTIAN',
   'RYSZNIVKIER JESICA',
   'ZALAZAR PAOLA',
   'CASTILLO CAROLINA',
   'SANTORO NESTOR',
   'AQUINO NORBERTO',
   'CASSIS CLAUDIA',
   'LOPEZ RICARDO',
   'FERRETTI CLAUDIA',
   'PACHECO MABEL',
   'BUTTAFUOCO, CESAR',
   'LIPARI GLADYS',
   'FERREIRO NESTOR',
   'SANTOS ANALIA',
   'VILLEGAS  CESAR',
   'KARIN EDUARDO DANIEL',
   'CHAIZAZ VALENZUELA TAMARA ',
   'BIANCHI ADRIAN',
   'GODINO RUBEN',
   'SUEIRO FERNANDO',
   'ARRUA CRISTINA',
   'MOOR LAURA CINTIA',
   'DABUL ARIADNA C.',
   'PENZA SILVINA',
   'LEDESMA CARINA',
   'YAZRA ALDO',
   'FORTE M. FLORENCIA',
   'JULIO MARIANA',
   'BUJANDA ROMINA',
   'USAI GABRIELA',
   'CEPURBEDA JORGE ',
   'MARTIRE VERONICA',
   'ARRIETA SILVIA',
   'JULIAN YAMIL',
   'NASELLI BRUNO',
   'BADRA JORGE',
   'ORTUBIA MABEL',
   'RIVAS GRACIELA',
   'SAVI MARIA EUGENIA',
   'CAMELINO  SUSANA',
   'SCARANO EMMANUEL',
   'RODRIGUEZ, MONICA',
   'MUNIZ CLAUDIO',
   'ESQUEFF ESTELA',
   'EXPOSITO JORGE',
   'ERMILIO MARIA ',
   'NIEMES GUILLERMO',
   'DUBOWSKI DEBORA  ',
   'DUBOWSKI DEBORA ',
   'PATANE GRACIELA',
   'CIOCCA ELEONORA',
   'GUEVARA LIA',
   'RIVEIRA SERGIO',
   'SALMON SILVANA',
   'LOPEZ MARIA CAROLINA',
   'ROUSSEAUX JULIETA',
   'BURGOS ROSA M.',
   'DRAGUNSKY MARCELO',
   'AVALLONE MARIA LAURA',
   'YANKELEVICH PABLO',
   'CHIRDO FLAVIA',
   'COTELLA CLAUDIA',
   'LA VALLE MAURICIO',
   'MONZON GRACIELA',
   'GRACIELA MONZON',
   'SIMEONE SILVIA',
   'ALVAREZ MARTIN',
   'ORTIZ BROSSARD IVANNA',
   'GUANO NICOLAS',
   'FIGLAS, FLAVIA',
   'PONTI CLAUDIA',
   'CALZONE ALEJANDRA',
   'NACCARI LILIANA',
   'COLOM SILVIA',
   'GARCIA LAURA',
   'RADICE KARINA',
   'YOCCO ELIDA ALICIA ALICIA',
   'BOGO MORALES MARIANO',
   'BOTTOLI OSCAR',
   'LOMBARDI ROMINA',
   'RUIZ, DANIEL ALBERTO',
   'QUIROGA MARIA FLORENCIA',
   'FISCHER MARIA BELEN',
   'ALSAMORA ALBERTO',
   'VALENZUELA LORENA',
   'BASUALDO MARCELA',
   'BALZANO CARLOS',
   'SANTILLAN PATRICIA',
   'PETRONE MARIA',
   'MOURELLE LAURA BEATRIZ',
   'SANTORO SILVIA',
   'LONGHI SILVIA',
   "D'ANTUONO OSVALDO",
   'ACHAGA PAOLA',
   'COGLIOLO ANALIA',
   'DAGLIO DANIELA',
   'MALAMUT DIEGO JAVIER',
   'VARCHIONI ANDREA',
   'VARDARO VANESA',
   'MESSINA SEBASTIAN',
   'MAGNO ANALIA PAULA',
   'CHIUSANO SERGIO',
   'NAVARRO LAURA',
   'VAZQUEZ CLAUDIO',
   'STABILE ALEJANDRO',
   'DOMINGUEZ MARIA LUZ',
   'ANDRADA ELEONORA',
   'KOLISNKI LAURA',
   'GUERRA MAGALI',
   'VILLA STELLA MARIS',
   'MARINO VIRGINIA',
   'ZALAZAR KARINA',
   'CONTRERAS MANUEL',
   'GRANDE GABRIEL',
   'MALDONADO SONIA',
   'RETO GIUNTA MARCELO',
   'SAAD FERNANDO',
   'MADELAIRE LUIS',
   'GARCIA LINARES GERARDO',
   'MERNES ELSIE',
   'DI RISIO DANIELA',
   'CANDIA SILVIA',
   'NICOLINO ORNELA',
   'OLIVERAS PATRICIA',
   'POMILIO MARIANA',
   'CHAIZAZ VALENZUELA TAMARA  ',
   'CRISOFOLI PABLO',
   'SILVA ALICIA ITATI',
   'MESSINA ADRIANA NOEMI',
   'DILEO VICTORIA',
   'SINARDI MARCELO',
   'ENTROCASSI PAOLA',
   'DIAZ GLADYS',
   'CALZONE SERGIO',
   'PRUBNER CYNTHIA',
   'DE CUNTO VERONICA',
   'ROMINA VALDEZ MILTOS',
   'VALDEZ MILTOS ROMINA',
   'MANCHINI PABLO',
   'PEZZELATO GABRIELA',
   'ALEGRE LUIS',
   'SIMUTIS ALEJANDRA',
   'RUBALDO DANIEL',
   'GUTIERREZ ALICIA',
   'MOLINA VALERIA',
   'CARMONA GUSTAVO',
   'ALADRO, JORGE',
   'IRALA ELSA ',
   'ONGARO JORGELINA',
   'BRONSTAIN JORGE',
   'IRALA ELSA  ',
   'TORRISI LUIS',
   'BARLETTA PAULA',
   'LICASTRO JOSE',
   'MORANDO GUSTAVO',
   'FAVARO LUCIANA',
   'REZK FRANCISCO',
   'DI TIERI JUAN',
   'BUONO ANA',
   'WASSOUF GERMAN',
   'SANSOLINI DIEGO',
   'CRISPINO PAULO',
   'ETCHEVERRY FERNANDO',
   'GONZALEZ CRISTINA',
   'GARCIA PABLO DANIEL',
   'GASTON GUTIERREZ',
   'GUTIERREZ GASTON',
   'ARAYA, JAVIER',
   'NEGRETTI NANCY',
   'ORQUIN MARIA F',
   'ALMADA CARMEN',
   'VALDES DAMIAN',
   'ROSSO ELENA',
   'ORQUIN M.FERNANDA',
   'SCHENONE MARIA OFELIA',
   'ALEGRE PAOLA',
   'AYERBE SILVIO',
   'CARRERA WALTER',
   'VILAR LEANDRO',
   'CLOCCHIATTI M. CECILIA',
   'PROCUPEZ CLAUDIO',
   'DE LUSARRETA MARTIN',
   'KALEKA RUTH',
   'BLANCO RAUL',
   'CAPARRA MARCELA',
   'LAMANA ANALIA',
   'JURI VELIZ GISELA',
   'VANESA LOMBARDO',
   'LOMBARDO VANESA',
   'COLUCCIO JORGE    ',
   'COLUCCIO JORGE  ',
   'NATALE VINCENZO',
   'CICCONE GISELA',
   'SANTORO MARTIN',
   'BUONO ANA MARIA',
   'CESTER DANIEL',
   'CAMELINO SUSANA',
   'SAGOL VALERIA',
   'FAIRCHILD JORGE',
   'RIVERO TERRAZAS NOEMI',
   'PEREZ GUSTAVO',
   'BURGOS MARCELA',
   'GARCIA ARECHA LUIS',
   'TECAZINER LUIS',
   'BERNARDEZ CARLOS',
   'ZANARDI CRISTINA',
   'COHEN LEONOR  ',
   'MOYA PATRICIA',
   'BERNARDO ALICIA',
   'VILLACORTA MARIA',
   'OVIEDO KARINA',
   'FIASCHE RUBEN',
   'BOGIN VERONICA',
   'TROVATO ROMINA',
   'FINOCHIETTI VANESA',
   'MANDEL MARIO',
   'PANELO CLAUDIA',
   'TROBO LAURA',
   'PUGLIESE ADRIANA',
   'GONZALEZ LAURA',
   'BORRI ROMINA',
   'CIGNONI ALEJANDRA',
   'CHICHIZOLA MARIA J.',
   'GROSSI GUILLERMO',
   'ARAMAYO FERNANDO',
   'MORANO ADOLFO',
   'DICOSTA LILIA',
   'BAREIRO JUANA',
   'VILLEGAS  ',
   'VILLEGAS ',
   'ZOCCALI JOSE LUIS',
   'FUERTES SANDRA',
   'MERLO CESAR',
   'VUOTTO GUSTAVO',
   'BONAVITA MARCELA',
   'DELL AGNOLO FLORENCIA',
   'SZUMOWSKI CAROLINA',
   'SEDANO FERNANDA',
   'AROZTEGUI PATRICIA',
   'FERREYRA CARLOS',
   'POSE LUCIANA',
   'FERNANDEZ BEATRIZ',
   'ASMUS MERCEDES',
   'MERA ANDREA',
   'CERRUTI PATRICIA ',
   'SGARBOSSA VALERIA',
   'FERRARI JAVIER',
   'MANGANARO CLAUDIO',
   'BURGOS MAGDALENA',
   'FERRARO LAURA',
   'BOSANO VALERIA',
   'FLAVIA FIGLAS',
   'GALVEZ GRISELDA',
   'PEREYRA CYNTHIA',
   'TRAVERSA NATALIA',
   'DE LUCA ANDREA',
   'FORTUNA MARIA LAURA',
   'ZARAGOCI SEBASTIAN',
   'SALVADOR M. EUGENIA',
   'AJARGO MARIA LAURA',
   'GIACUSA MARIA ALEJANDRA',
   'PALOMINO VERONICA',
   'GARCIA PAOLA',
   'TEMPONE CAROLINA',
   'BEITONE VANESA',
   'PEREZ ROSANA',
   'ROMANO DANIEL',
   'BERNUES PLINIO',
   'DUJO ANDREA FABIANA',
   'ALEGRE SOLEDAD',
   'TORRE ANDREA',
   'SUAREZ MARIA',
   'AREN MARIA EVA',
   'DIAZ ERIKA',
   'TRANI CLAUDIA',
   'LOPEZ KADAR MARCELO',
   'ALEGRE NATALIA',
   'BAJO HERNAN',
   'TASSI LILIANA',
   'ZOILO JUAN',
   'CASTA?EDA VIVIANA',
   'FERNANDEZ LAVIA JOAQUIN',
   'ALVAREZ BEATRIZ',
   'VAINER PABLO',
   'BENAVIDEZ MIRNA SAMANTA',
   'CERRUTI PATRICIA  ',
   'ORTIZ IVANNA',
   'OUTON JULIO',
   'AGOSTINI MARIANA',
   'GOMEZ NELIDA',
   'BELTRAMONE INES',
   'SALDANERI GISELLA',
   'TROTTA DIEGO',
   'NEME CAROLINA',
   'CALVANI ALDANA',
   'LESCANO MONICA',
   'MOSCOLONI MONICA',
   'TUSTANOSKI MARCELO',
   'CORREA GUSTAVO',
   'AGUIRRE FLAVIA',
   'VALENZUELA EMMANUEL',
   'TORRES ALICIA',
   'DIAZ ERIKA ',
   'DEL RIO VERONICA',
   'GOMEZ YAMILA',
   'BIELAT EUGENIO',
   'PERTA AURELIA',
   'CASTIGLIONE ROMINA',
   'BIANCO FIORELLA',
   'PI?EIRO CARINA',
   'ROMERO JORGE',
   'BIANCHI CLAUDIO',
   'ZATELLI VALERIA',
   'ALVAREZ PABLO',
   'OUTON JULIO ',
   'ROMERO GERMAN',
   'TORRISI GRISELDA',
   'PANTANO HORACIO',
   'BARLETTA MARIA PAULA',
   'MANCHINI HERNAN',
   'ALVAREZ DANIEL',
   'PEREZ PATRICIA',
   'RUIZ RICARDO',
   'MADELAIRE LUIS ',
   'EDREIRA NORMA',
   'SILVIA MARIANA LOBO',
   'LOBO SILVIA MARIANA',
   'PRADO EVA',
   'MONTERO FERNANDO',
   'ERMILIO MARIA  ',
   'CAPUTO ROMINA',
   'MILAN ORDOQUI JAVIER',
   'LAURA GARCIA',
   'RUIZ SILVINA',
   'MESITI CLAUDIO',
   'GIACUSA ALEJANDRA',
   'BIANCHI M FERNANDA',
   'PATANE ALICIA',
   'YOCCO ELIDA ALICIA',
   'BATTAGLIA ROSARIO',
   'YA?EZ NORA',
   'MARIA LAURA FORTUNA',
   'TEMOCHE VICTOR',
   'AGUILAR DOMINGO ALBERTO',
   'DUARTE INCHAUSTI FEDERICO',
   'MARIANA MARTINEZ',
   'URBANEJA ESTER',
   'LOPEZ M. CAROLINA',
   'ARAMBURU GERMAN',
   'FERRO FERNANDO',
   'GARCIA STELLA',
   'MILMAN MARIANO',
   'SOUTO CARLOS',
   'CARLOS SOUTO',
   'CISNERO DIEGO',
   'MARTINUZZI SERGIO '],
  'SUPERVISOR': ['ARFUSO VIVIANA',
   'PATANE ALICIA',
   'MERA ANDREA',
   'ALVAREZ PABLO',
   'ZOCCALI JOSE LUIS',
   'ALFARO NADIA',
   'CAPUTO ROMINA',
   'BOTANA ANTONIO',
   'ALVAREZ MARTIN',
   'MARTINEZ MARIANA',
   'BREPPE MARISA',
   'PEREZ PATRICIA',
   'POLICANO, ANTONIO',
   'FERNANDEZ JUAN',
   'PETRELLA ANTONIO',
   'GONIONDZKY SILVINA',
   'BEITONE VANESA',
   'GIAMMARCHE DANIEL',
   'RIVERO CLAUDIA',
   'POLICANO ANTONIO',
   'BIANCHI MARIA FERNANDA',
   'BARBAGELATA RODOLFO',
   'RUBIO MARCELO',
   'FIORENZA GUSTAVO',
   'GONZALEZ CLAUDIA',
   'ATANIYA DIEGO',
   'LEGUIZAMON EMANUEL',
   'GUMUCIO HUMBERTO',
   'LENGARD CRISTINA',
   'CISNERO DIEGO',
   'SPERONI MARCELO',
   'COLUCCIO JORGE',
   'ANTONELLI MARTA',
   'CEPURBEDA JORGE',
   'MILMAN MARIANO',
   'PINTO JORGE',
   'MARTIN CAROLINA',
   'GARCIA STELLA MARIS',
   'CEREZO MARCELA',
   'ALVAREZ DANIEL',
   'SOUTO CARLOS',
   'CARLOS SOUTO',
   'MELILLO MARCELO',
   'ABELARDO ROMINA',
   'ROMERO GUADALUPE',
   "D'APICE ADRIANA",
   'POSE LUCIANA',
   'SANTORA ALEJANDRO',
   'TRICOTTI GABRIELA',
   'GARIB JOSE LUIS',
   'EDREIRA NORMA',
   'GARIB JOSE LUIS LUIS',
   'AIELLO EDUARDO',
   'GONZALEZ MAURO',
   'LASPINA ROXANA',
   nan,
   'MONTERO FERNANDO',
   'MANCHINI HERNAN',
   'DOMINGUEZ JAVIER',
   'ARAMBURU GERMAN',
   'SANZ HORACIO',
   'BALZANO CARLOS',
   "D'AMICO VANINA",
   'CAPARRA MARCELA',
   'FERNANDO MONTERO',
   'SALLES ENRIQUE',
   'ZELVYS SERGIO',
   'VAZQUEZ MARTINEZ GUSTAVO',
   'BECERRA PEREZ HUGO',
   'VALDEZ RAUL',
   'GERMAN ARAMBURU',
   'CHIRICO MARIA',
   'SOLODUJIN VANINA',
   'JULIAN YAMIL',
   'COHEN LEONOR',
   'BECERRA HUGO',
   'SANCHEZ ARIAS HILDA',
   'CHAIN JORGE',
   'CLAUDIA GONZALEZ'],
  'RAZON_SOCIAL': ['07 B A TEX SRL',
   '1001 FARDO SRL',
   '151 SRL',
   '24 HORAS SA',
   '25 HORAS SA',
   '3M ARGENTINA SACIFIA',
   '4 M SOCIEDAD DE RESPONSABILIDAD LTDA',
   '5CA SA',
   '5TH ESSENCE S.A',
   'A J MENDIZABAL Y CIA SACYAF',
   'A M SEGURIDAD SRL',
   'A NOVO ARGENTINA SA',
   'A RUSSONIELLO SA',
   'A Y M DESPOSITO SRL',
   'A Y S SERVICIOS INTEGRALES SA',
   'A ZAEL SA',
   'ABACK SA',
   'ABADI RUBEN HECTOR',
   'ABAS VICTOR OSVALDO',
   'ABASTO NUEVO SA',
   'ABBOTT LABORATORIES ARG SA',
   'ABC VIAL SRL',
   'ABD SA',
   'ABENIA PEREYRA',
   'ABERTURAS LIBERTADOR SA',
   'ABM CONSTRUCTORA SA',
   'ABOUD MOISES JOSE',
   'ABRIL MED SA',
   'ABUCA SA',
   'ABYMES SA',
   'AC ANDRE CARGAS SRL',
   'AC BLANCO SA',
   'AC METAL SA',
   'ACAYU SRL',
   'ACCESO DIRECTO SA',
   'ACCION PROMOCIONAL SRL',
   'ACE AMERICAN INSURANCE',
   'ACE SEGUROS SA',
   'ACECO ARGENTINA SA',
   'ACEGAME SA',
   'ACEITERA DEL SUR SA',
   'ACERBELT SA',
   'ACERCAR VIAJES SRL',
   'ACEROBUENO SA',
   'ACEROS ANGELETTI SA',
   'ACEROS SUD  SA',
   'ACEVEDO TOLINDA',
   'ACO COLOR SA',
   'ACOPLADOS SALTO SA',
   'ACP SEGURIDAD SA',
   'ACUARELA ULTRA MODA SA',
   'ACUARIO EVENTOS Y PROMOCIONES SA',
   'ACUAVIT SA',
   'ACU?A CUADROS YOLANDA',
   'ADAMS MARIA ALEJANDRA',
   'ADAN BS AS SRL',
   'ADANO JORGE ENRI',
   'ADCA SA',
   'ADELAAR SA',
   'ADELIDE SA',
   'ADIDAS ARGENTINA SA',
   'ADILA SA',
   'ADM DE MONEDEROS ELECTRONICOS SA',
   'ADMINISTRACION GENERAL DE PUERTOS SOC DEL ESTADO',
   'ADMINISTRADORA DE MONEDERO ELEC SA',
   'ADMINISTRAR SALUD SA',
   'ADMIRALTY SA',
   'ADOLFO PATANCHON',
   'ADOM SA',
   'ADPE SA',
   'ADRIAN MERCADO SA',
   'ADROGUE BUS SRL',
   'ADVANTA SEMILLAS SAIC',
   'ADVENT ARGENTINA SRL',
   'AEROPUERT ARG 2000',
   'AESA SA FOM. Y CONT. SA UTE',
   'AFERSA SA',
   'AFIANZADORA LATINOAMERICANA COPA?IA DE SEGUROS SA',
   'AFINA SRL',
   'AG PRUDEN Y CIA SACIFIA',
   'AGAPE SERVICIO GASTRONOMICO SA',
   'AGAZZI AGUSTIN HERNAN',
   'AGENLUX SA',
   'AGIMED SRL',
   'AGIR SRL',
   'AGM MOTOS SRL',
   "AGNIE FRANCAISE D'ASSURANCE POUR LE COMMERCE EXTERIOR SUC",
   'AGO ROPA SA',
   'AGOSTINO JAVIER C',
   'AGRI FOOD SA',
   'AGRICOLA GANADERA DE SAN BOROMBON SA',
   'AGRIPER SA',
   'AGRO RAP SRL',
   'AGRO SHEEP SRL',
   'AGRO TRADER INC SRL',
   'AGROBEL FRUITS SA',
   'AGROCEREALES DEL PLATA SA',
   'AGROCOMERCIAL NOA SA',
   'AGROCOMODITIES SA',
   'AGROFINA SA',
   'AGROFLEX SA',
   'AGROINDUSTRIAS CIALPIL SA',
   'AGROLUCAS SA',
   'AGROMANI SA.',
   'AGROSERVICIOS CAPDEVIELLE SA',
   'AGROSERVICIOS PAMPEANOS SA',
   'AGROSUR NEGOCIOS INTEGRADOS SA',
   'AGU SRL',
   'AGUA Y SANEAMIENTOS ARG. SA (AYSA)',
   'AGUARIBAY SA',
   'AGUAS DANONE ARGENTINA SA',
   'AGUILAR VILMA GREGORIA',
   'AGUINOR SRL',
   'AHUMADA MARIANELA AZUCENA',
   'AILLING SA',
   'AIR COOL SA',
   'AIR LIQUIDE ARGENTINA SA',
   'AIR SRL',
   'AIRA DANIEL EDUARDO',
   'AIS APLICACIONES DE INTELIGENCIA ARTIFICIAL SA',
   'AISENBERG DANIEL',
   'AITOR IDER BALBO SAACEI',
   'AJUCAR SRL',
   'AKZO NOBEL FUNCTION CHEMICALS',
   'ALADDIN SRL',
   'ALAKEFAK SRL',
   'ALBA COMPA?IA ARGENTINA DE SEGUROS SA',
   'ALBANDOZ PABLO IGNACIO',
   'ALBERTO LUIS POZO',
   'ALBOCAR SRL',
   'ALBOSA SRL',
   'ALCON TORREZ PAULINO',
   'ALDACUR JOSE MARIA',
   'ALECOLOR SRL',
   'ALEDI SUR SRL',
   'ALEJO JAVIER ZACARIAS',
   'ALENCO SAIC',
   'ALETAN SRL',
   'ALFA ENERGIA SA',
   'ALFA LAVAL SA',
   'ALFA RACKS SA',
   'ALFAR CONSTRUCCIONES SA',
   'ALFERCARD SRL',
   'ALFONSIN BARREIRO MANUEL',
   'ALGODONERA SANTA FE SA',
   'ALHADEFF ALEJANDRO MOISES',
   'ALI JORGE OMAR',
   'ALI PHARMA SRL',
   'ALICORP ARGENTINA SA',
   'ALIERS SA',
   'ALIMENTOS GENERALES SA',
   'ALIMENTOS SURE?OS SA',
   'ALIMENTOS VIDA SA',
   'ALIO ALBERTO ENRIQUE',
   'ALISEC SAC',
   'ALIWEN INCOMING SRL',
   'ALL DENIM SA',
   'ALL IMPORT SA',
   'ALLEGRINI MARCELO ATILIO',
   'ALLENDE MARTA FERNANDA',
   'ALLIANZ ARGENTINA COMPANIA DE SEGUROS SA',
   'ALLIANZ RE ARGENTINA SA',
   'ALMADA ARMANDO NESTOR',
   'ALPARGATAS SAIC',
   'ALPHA GRAPHIC SRL',
   'ALPINA MOTORS SRL',
   'ALQUIMIA INSTITUCIONAL SRL',
   'ALRA SA',
   'ALTA DENSIDAD SRL',
   'ALTO PALERMO SA APSA',
   'ALTO PARANA SA',
   'ALTOS CEREALES  SRL',
   'ALVAMOS SA',
   'ALVARADO RECAUDACIONES SRL',
   'ALVAREZ JOSE LUIS',
   'ALVAREZ THOMAS 12 SRL',
   'ALVAREZ Y PATI?O SA',
   'ALVEAR PALACE HOTEL SA',
   'ALZA GROUP SA',
   'ALZAGA UNZUE Y CIA SA',
   'AMABILE E HIJOS SRL',
   'AMACON TOURS SRL',
   'AMADEUS ARGENTINA SA',
   'AMADO, MIGUEL MEZA',
   'AMAFREN SA',
   'AMANCAY SAICAFI',
   'AMANTO JORGE ALBERTO',
   'AMARU SA',
   'AMBAR CIA MINERA SA',
   'AMERICA AUTOPIEZAS SA',
   'AMERICA BLINDAJES SA',
   'AMERICA BOX SA',
   'AMERICA LATINA LOGISTICA CENTRAL SA',
   'AMERICA LATINA LOGISTICA MESOPOTAMICA SA',
   'AMERICAN COTTON',
   'AMERICAN EAGLE SRL',
   'AMERICAN EXPRESS SA',
   'AMERICAN HOME ASSURANCE COMPANY',
   'AMERICAN TRACER SA',
   'AMERINODE SRL',
   'AMERISE NORA CONCEPCION CATALINA',
   'AMIPLAST S.H. DE ROQUE AMIANO Y M. AMIANO',
   'AMISON SA',
   'AMSHEL SA',
   'AMUR CAR SA',
   'AMUSH SA',
   'AMX ARGENTINA SA',
   'ANCOCIA SA',
   'ANDRE SUSANA ALICIA',
   'ANDREA LAURA FORES TACCA',
   'ANDRES JORGE',
   'ANDRES MORETTI E HIJOS SA',
   'ANGEL MARCELO GABRIEL',
   'ANGELES ACOSTA ANTONIO PEDRO',
   'ANGIOCOR SA',
   'ANGLOS SA',
   'ANILE RAQUEL',
   'ANONIMATO SA',
   'ANSELMO L MORVILLO SA',
   'ANTARTIDA CIA ARG DE SEGUROS SA',
   'ANTARTIS SRL',
   'ANTHOLOGY SA',
   'ANTOLIN MARTIN',
   'ANUNTIS SEGUNDAMANO ARGENTINA SA',
   'ANZURUT JULIA',
   'A?ON JOSE ALBERTO',
   'AODA SA',
   'AON RE ARGENTINA BENFIELD ARGENTINA SA',
   'APARICIO JORGE NESTOR',
   'APPAREL ARGENTINA SA',
   'AQUIN ARMANDO MIGUEL',
   'AR CLEPPE Y CIA SA',
   'ARA EDITORIAL IMPRESORA SRL',
   'ARACA BENAVIDEZ VICTOR',
   'ARAMBILLETE VILLAR JOSE',
   'ARANCIBIA HUGO ERNESTRO',
   'ARAUCAR MOTORS SA',
   'ARCA DISTRIBUCIONES SA',
   'ARCADI SA',
   'ARCOMAN MAGDALENA',
   'ARCOR SAIC',
   'ARCOS DEL GOURMET SA',
   'ARCOS DORADOS SA',
   'AREA EDITORIAL IMPRESORS SRL',
   'AREDA SRL',
   'ARENA ARGENTINA SA',
   'ARENALES 1842 VELSUD SA',
   'ARENERA GENERAL LAVALLE SA',
   'ARENERA JEANPIERRE SA',
   'ARENERA VENDAVAL SA',
   'ARENERA VIRAZON SA',
   'ARETINA SOCIEDAD ANONIMA',
   'AREVALO 1906 SA',
   'ARFINSA ARGENTINA FINANCIERA SA',
   'ARGENCEL SA',
   'ARGENIT SA',
   'ARGENPOSTAL SRL',
   'ARGENPROM SRL',
   'ARGENTINA COLOR SRL',
   'ARGENTINA SPORTS & TRAVEL SRL',
   'ARGENTINAIR SA',
   'ARGENTO DARDO GABRIEL OLMOS PABLO',
   'ARGENTOL SA',
   'ARGOS CIA DE SEGUROS GENERALES SA',
   'ARIAS HORACIO RUBEN',
   'ARIES CINAMATOGRAFICA ARGENTINA SA',
   'ARIMER SRL',
   'ARKAY SA',
   'ARKINO SA',
   'ARL SA',
   'ARMANDO J.RIOS SA',
   'ARMOR LATINA SA',
   'ARMOR SRL',
   'ARMORAUT SA',
   'AROMA CAFE SA',
   'AROMAS DEL BOTANICO SRL',
   'ARONSON CLAUDIO ARIEL',
   'ARPINI LEONARDO LUIS',
   'ARPRON SA',
   'ARQUIMEX SACEI',
   'ARQUIMIA SA',
   'ARREDO SA',
   'ARROW SERVICIOS SRL',
   'ARROYO GRACIELA MAGDALENA',
   'ARTE ENCUADERNACION SRL',
   'ARTELTEX SRL',
   'ARTELUM SA',
   'ARTES CONTINUAS SRL',
   'ARTES DENTALES SRL',
   'ARTES GRAFICAS ALEXANDER FLEMING SA',
   'ARTES GRAFICAS NEGRI SRL',
   'ARUBRAS SA',
   'ARUMBILLETE VILLAR J. MARIA',
   'ARUNI CONDORI ADRIAN',
   'ARYVA SA',
   'ASA BAHIA SA',
   'ASAHI MOTORS SA',
   'ASCARRAGA GABRIELA ALEJANDRA',
   'ASCENSORES BIANCHINI SRL',
   'ASCENSORES SERVAS SA',
   'ASEG.DE CRED. GARANTIAS SA',
   'ASEGURADORA DE RIESGOS DEL TRABAJO LIDERAR',
   'ASEGURADORA TOTAL MOTOVEHICULAR SA',
   'ASEGURADORES DE CAUCIONES SA',
   'ASESORAMIENTO TECNOLOGICO SA',
   'ASESORES FINANCIEROS ASOCIADOS',
   'ASHIR TECHNOLOGY CORP SRL',
   'ASHIRA SA',
   'ASHIRA SA MARTIN Y MARTIN SA UTE',
   'ASISGER SRL',
   'ASLAN Y EZCURRA SA',
   'ASMEC SRL',
   'ASOC ARG DE PROTECCION DE LAS OBT VEGETALES (ARPOV)',
   'ASOC. ARG. DE PROTECCION DE LAS OBTENCIONES VEGETALES',
   'ASOC. CIRCULO ITALIANO',
   'ASOPROFARMA AOSC PROP DE FARMACIAS COOP PROVENSIN',
   'ASSIST CARD ARGENTINA SA DE SERV.',
   'ASSURANT ARGENTINA COMPA?IA DE SEGUROS SA',
   'ASTILLEROS NEPTUNO SA',
   'ASTORI ESTRUCTURAS SA',
   'ASV ARGENTINA SA',
   'AT HOME SRL',
   'ATACAMA FERIAL SA',
   'ATENCION AMBULATORIA SA',
   'ATENTO ARGENTINA SA',
   'ATMED SRL',
   'ATOMLUX SRL',
   'ATRIM ARGENTINA SA',
   'ATS ADVANCED TECHNOLOGY SA',
   'ATSINOISI SA',
   'ATTAR OMAR LORENZO',
   'ATTO SRL',
   'AUDIOPTICA INTERNACIONA SA',
   'AUDITORIO DE BUENOS AIRES SA',
   'AUGEMI SRL',
   'AUGRAF SRL',

### Verificaciion ortografia española de los valores

In [6]:
# Para analizar la ortografía en español de las columnas se puede usar la siguiente función e instalar la librería fuzzywuzzy

import sys
print(sys.path)


import re
from fuzzywuzzy import fuzz


def ortografia_columnas(df):
    columnas = df.columns
    columnas = [re.sub(r'[^a-zA-Z0-9 ]', '', columna) for columna in columnas]
    columnas = [columna.lower() for columna in columnas]
    columnas = [columna.replace(' ', '') for columna in columnas]
    columnas = [columna for columna in columnas if columna != '']
    columnas = list(set(columnas))
    ortografia = []
    for columna in columnas:
        if fuzz.ratio(columna, 'año') < 90:
            ortografia.append(columna)
    return ortografia

print("-------------------------")  
print("Ortografía de las columnas")
print("-------------------------")  
print(ortografia_columnas(df))

['c:\\Users\\20927322707\\Desktop\\analizador_datasets\\Analizador', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\python312.zip', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\DLLs', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3', '', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages\\win32', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages\\win32\\lib', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages\\Pythonwin', 'c:\\Users\\20927322707\\AppData\\Local\\anaconda3\\Lib\\site-packages\\setuptools\\_vendor']

ModuleNotFoundError: No module named 'fuzzywuzzy'

In [3]:
# Se crea un objeto de la clase CalidadDatos con los datos de interés
ruta_covid = "dataset ejemplos.xlsx"
datos_covid = CalidadDatos(ruta_covid)

C:\Users\jairoruiz\Documents\GitHub\leila_env\lib\site-packages\leila\calidad_datos.py:1307: UserWarning: Cargar archivos xlsx puede tomar demasiado tiempo, se aconseja fuertemente convertirlos a archivo csv, esto puede mejorar hasta 100x veces la velocidad de carga del archivo dataset ejemplos.xlsx
  "Cargar archivos xlsx puede tomar demasiado tiempo, se aconseja "

#### 1. Tabla de resumen
El método "resumen" calcula varias estadísticas que dan una primera impresión del conjunto de datos. 

Estas métricas incluyen el número de filas y columnas; número de columnas de distintos tipos; número de filas y columnas repetidas (duplicadas); columnas con muchos datos faltantes o extremos; peso del conjunto de datos

#### 2. Tipos de cada columna
El método "TipoColumnas" calcula el tipo de cada columna de tres maneras diferentes. 

La primera es el tipo general de la columna en español. Indica si el tipo es numérico, texto, fecha, booleano u otro

La segunda muestra el tipo general según el método dtypes de Python.

La tercera manera muestra los tipos de cada celda de cada columna. Es decir, muestra la distribución de tipos de cada columna. El tipo que más aparece en esa columna se muestra en la variable "tipo_especifico_1" de la tabla de tipos y muestra el porcentaje. En caso de haber más de un tipo, se mostrará en las siguientes columnas "tipo_especifico_#"

El ejemplo abajo muestra cómo el es código para generar los resultados de los tipos con el método "TipoCOlumnas". Los parámetros del método especifican qué tipo se quiere mostrar para las columnas (con las opciones True o False)

In [5]:
tipos = datos_covid.TipoColumnas(tipoGeneral=True, 
                                 tipoGeneralPython=True, 
                                 tipoEspecifico=True)
tipos

,tipo_general,tipo_general_python,tipo_especifico_1,tipo_especifico_2
ID de caso,Texto,string,'str': 100.0%,
Fecha de notificación,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 10...,
Código DIVIPOLA,Texto,string,'str': 100.0%,
Ciudad de ubicación,Texto,string,'str': 100.0%,
Departamento o Distrito,Texto,string,'str': 100.0%,
Atención,Texto,string,'str': 99.71%,'pandas._libs.missing.NAType': 0.29%
Edad,Numérico,Int64,'int': 100.0%,
Edad 2,Numérico,Int64,'int': 100.0%,
Edad meses,Numérico,Int64,'int': 100.0%,
Sexo,Texto,string,'str': 100.0%,
Tipo,Texto,string,'str': 100.0%,
Estado,Texto,string,'str': 99.66%,'pandas._libs.missing.NAType': 0.34%
País de procedencia,Texto,string,'pandas._libs.missing.NAType': 98.58%,'str': 1.42%
Fecha de inicio de síntomas,Texto,string,'str': 100.0%,
Fecha de muerte,Fecha,datetime64[ns],'pandas._libs.tslibs.nattype.NaTType': 95.38%,'pandas._libs.tslibs.timestamps.Timestamp': 4.62%
Fecha diagnostico,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 98...,'pandas._libs.tslibs.nattype.NaTType': 1.59%
Fecha recuperado,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 91...,'pandas._libs.tslibs.nattype.NaTType': 8.67%
Fecha reporte web,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 10...,
Fecha de registro,Fecha,datetime64[ns],'pandas._libs.tslibs.timestamps.Timestamp': 10...,
Tipo recuperación,Texto,string,'str': 91.33%,'pandas._libs.missing.NAType': 8.67%
Codigo departamento,Texto,string,'str': 100.0%,
Codigo pais,Texto,string,'pandas._libs.missing.NAType': 98.65%,'str': 1.35%
Pertenencia etnica,Texto,string,'str': 98.13%,'pandas._libs.missing.NAType': 1.87%
Nombre grupo etnico,Texto,string,'pandas._libs.missing.NAType': 97.97%,'str': 2.03%
Diccionario,Texto,string,'str': 100.0%,

#### 3. Datos faltantes

El método "ValoresFaltantes" permite calcular el número o porcentaje de valores faltantes de un conjunto de datos. Si el parámetro "numero" tiene asignado el valor True, se calcula el número de valores faltantes de cada columna. De lo contrario, si es False, se calcula el porcentaje.

El ejemplo a continuación presenta los porcentajes de datos faltantes de cada columna del conjunto de datos de COVID-19

In [6]:
faltantes = datos_covid.ValoresFaltantes(numero = False)
faltantes

ID de caso                     0.000000
Fecha de notificación          0.000000
Código DIVIPOLA                0.000000
Ciudad de ubicación            0.000000
Departamento o Distrito        0.000000
Atención                       0.002941
Edad                           0.000000
Edad 2                         0.000000
Edad meses                     0.000000
Sexo                           0.000000
Tipo                           0.000000
Estado                         0.003414
País de procedencia            0.985766
Fecha de inicio de síntomas    0.000000
Fecha de muerte                0.953837
Fecha diagnostico              0.015941
Fecha recuperado               0.086701
Fecha reporte web              0.000000
Fecha de registro              0.000000
Tipo recuperación              0.086701
Codigo departamento            0.000000
Codigo pais                    0.986512
Pertenencia etnica             0.018745
Nombre grupo etnico            0.979685
Diccionario                    0.000000
dtype: float64

#### 4. Datos duplicados

El método "CantidadDuplicados" calcula el número o porcentaje de duplicados en el conjunto de datos. 

El ejemplo abajo calcula el número de duplicados para filas y columnas del conjunto de datos de COVID-19.

In [7]:
# Número de filas duplicadas. 
# Se escribe el parámetro eje = 0, para especificar fila
# Se escribe el parámetro numero = True, para especificar el número de duplicados (si es False se calcula el porcentaje)
filas_duplicadas = datos_covid.CantidadDuplicados(eje = 0, numero = True)

# Número de columnas duplicadas. 
# Se escribe el parámetro eje = 1, para especificar columna
# Se escribe el parámetro numero = False, para especificar el porcentaje de duplicados
columnas_duplicadas = datos_covid.CantidadDuplicados(eje = 1, numero = True)

print("Filas duplicadas: ", filas_duplicadas)
print("Columnas duplicadas: ", columnas_duplicadas)

Filas duplicadas:  1
Columnas duplicadas:  2

#### 5. Emparejamiento de duplicados
El método "EmparejamientoDuplicados" permite mostrar los nombres de filas o columnas que son exactamente iguales. El parámetro "col" especifica si se quieren emparejar los duplicados de filas al asignarlo a False. Para emparejar las columnas se escribe True.

EL ejemplo abajo muestra los nombres de las filas duplicadas en cada columna de la tabla. Por ejemplo, la columna de la tabla "Filas iguales 1" muestra que las filas 1 y 2 son duplicadas.

In [8]:
emparejamiento_dupli_filas = datos_covid.EmparejamientoDuplicados(col = False)
emparejamiento_dupli_filas

   Filas iguales 1
0              267
1              269

EL ejemplo abajo muestra los nombres de las columnas duplicadas en cada columna de la tabla. Por ejemplo, la columna de la tabla "Columnas iguales 1" muestra que las columnas "Edad" y "Edad 2" son duplicadas

In [9]:
emparejamiento_dupli_cols = datos_covid.EmparejamientoDuplicados(col = True)
emparejamiento_dupli_cols

  Columnas iguales 1 Columnas iguales 2
0               Edad  Fecha reporte web
1             Edad 2  Fecha de registro

#### 6. Estadísticas descriptivas de variables numéricas

El método DescripcionNumericas permite calcular estadísticas descriptivas para variables numéricas tales como el promedio, la desviación estándar, el mínimo, máximo, mediana (percentil 50), valores faltantes y extremos. 

El objetivo de estos cálculos es verificar si las variables del conjunto de datos contienen los valores esperados o si existen errores en la digitación de los valores

El ejemplo abajo muestra las estadísticas descriptivas para las variables "Edad", "Edad_2" y "Edad meses"

In [10]:
descr_numericas = datos_covid.DescripcionNumericas()
descr_numericas

,count,mean,std,min,25%,50%,75%,max,missing,outliers_total,outliers_altos,outliers_bajos
Edad,65616.0,39.175536,18.661339,0.0,26.0,36.0,52.0,104.0,0.0,0.002865,0.002865,0.0
Edad 2,65616.0,39.175536,18.661339,0.0,26.0,36.0,52.0,104.0,0.0,0.002865,0.002865,0.0
Edad meses,65616.0,476.099625,223.962309,1.0,318.0,443.0,626.0,1250.0,0.0,0.004054,0.004054,0.0

Es posible calcular las estadísticas descriptivas para algunas variables únicamente. Esto se hace al asignar una lista con las variables de interés al parámetro "variales", como se muestra a continuación

In [11]:
descr_numericas = datos_covid.DescripcionNumericas(variables = ["Edad", "Edad meses"])
descr_numericas

,count,mean,std,min,25%,50%,75%,max,missing,outliers_total,outliers_altos,outliers_bajos
Edad,65616.0,39.175536,18.661339,0.0,26.0,36.0,52.0,104.0,0.0,0.002865,0.002865,0.0
Edad meses,65616.0,476.099625,223.962309,1.0,318.0,443.0,626.0,1250.0,0.0,0.004054,0.004054,0.0

#### 7. Estadísticas descriptivas de variables categóricas
El método DescripcionCategoricas calcula la frecuencia, tanto en número como en porcentaje del total de filas, de los valores de las variables que se consideran numéricas. 

Las variables se consideran categóricas si contienen valores limitados. Por defecto, el máximo número de categorías es 30 y las categorías no pueden representar más del 50% del total de filas de la columna. Estos valores se pueden modificar en los parámetros "limite" y "categoriasMaximas" del método "DescripcionCategoricas". 

Es posible también especificar si las variables numéricas con pocos valores se quieren incluir en el análisis. Por ejemplo, variables que contienen únicamente los números 1 y 2. Para agregar las variables al análisis, se asigna el valor True al parámetro incluirNumericas (el cual está por defecto) y False si no se desean incluir.

Por último, es posible agregar una lista limitada de variables al análisis, asignando una lista de Python con las variables al parámetro "variables"

El ejemplo abajo muestra cómo se calculan las frecuencias de categorías de variables categóricas con los parámetros del método DescripcionCategoricas por defecto

In [12]:
descr_categoricas = datos_covid.DescripcionCategoricas(limite=0.5, 
                                                       categoriasMaximas=30, 
                                                       incluirNumericos=True, 
                                                       variables=None)
descr_categoricas

,Columna,Valor,Frecuencia,Porcentaje del total de filas
0,Atención,Recuperado,59927.0,0.913299
1,Atención,Fallecido,2914.0,0.044410
2,Atención,Hospital,2138.0,0.032584
3,Atención,Hospital UCI,438.0,0.006675
4,Atención,Casa,6.0,0.000091
5,Atención,Datos faltantes,193.0,0.002941
6,Atención,Total categorías (incluye NA): 6,NaN,NaN
0,Sexo,M,35552.0,0.541819
1,Sexo,F,30056.0,0.458059
2,Sexo,f,6.0,0.000091
3,Sexo,m,2.0,0.000030
4,Sexo,Datos faltantes,0.0,0.000000
5,Sexo,Total categorías (incluye NA): 4,NaN,NaN
0,Tipo,En estudio,50836.0,0.774750
1,Tipo,Relacionado,13847.0,0.211031
2,Tipo,Importado,933.0,0.014219
3,Tipo,Datos faltantes,0.0,0.000000
4,Tipo,Total categorías (incluye NA): 3,NaN,NaN
0,Estado,Leve,52084.0,0.793770
1,Estado,Asintomático,6811.0,0.103801
2,Estado,Moderado,3135.0,0.047778
3,Estado,Fallecido,2914.0,0.044410
4,Estado,Grave,448.0,0.006828
5,Estado,Datos faltantes,224.0,0.003414
6,Estado,Total categorías (incluye NA): 6,NaN,NaN
0,Tipo recuperación,PCR,35370.0,0.539045
1,Tipo recuperación,Tiempo,24557.0,0.374253
2,Tipo recuperación,Datos faltantes,5689.0,0.086701
3,Tipo recuperación,Total categorías (incluye NA): 3,NaN,NaN
0,Pertenencia etnica,Otro,57670.0,0.878901
1,Pertenencia etnica,Negro,5003.0,0.076247
2,Pertenencia etnica,Indígena,1333.0,0.020315
3,Pertenencia etnica,Rom,293.0,0.004465
4,Pertenencia etnica,Raizal,72.0,0.001097
5,Pertenencia etnica,Palenquero,15.0,0.000229
6,Pertenencia etnica,Datos faltantes,1230.0,0.018745
7,Pertenencia etnica,Total categorías (incluye NA): 7,NaN,NaN
0,Diccionario,{1},32808.0,0.500000
1,Diccionario,{2},32808.0,0.500000
2,Diccionario,Datos faltantes,0.0,0.000000
3,Diccionario,Total categorías (incluye NA): 2,NaN,NaN

#### 8. Peso de las variables en la memoria RAM
Para calcular cuál es el peso de cada variable, se utiliza el método "Memoria", como se muestra en el ejemplo abajo. El parámetro "unidad" indica que se quiere calcular en Mega Bytes ("Mb") y el parámetro "col" indica que se calcula para cada variable. En caso de desear calcular el peso total del conjunto de datos, se asigna False al parámetro "col".

In [13]:
peso_memoria = datos_covid.Memoria(col=True, unidad="Mb")
peso_memoria

Index                          0.000122
ID de caso                     0.500610
Fecha de notificación          0.500610
Código DIVIPOLA                0.500610
Ciudad de ubicación            0.500610
Departamento o Distrito        0.500610
Atención                       0.500610
Edad                           0.563187
Edad 2                         0.563187
Edad meses                     0.563187
Sexo                           0.500610
Tipo                           0.500610
Estado                         0.500610
País de procedencia            0.500610
Fecha de inicio de síntomas    0.500610
Fecha de muerte                0.500610
Fecha diagnostico              0.500610
Fecha recuperado               0.500610
Fecha reporte web              0.500610
Fecha de registro              0.500610
Tipo recuperación              0.500610
Codigo departamento            0.500610
Codigo pais                    0.500610
Pertenencia etnica             0.500610
Nombre grupo etnico            0.500610
Diccionario                    0.500610
dtype: float64

#### 9 Correlación entre variables numéricas

El método "CorrelacionNumericas" calcula una matriz de correlación entre las variables numéricas del conjunto de datos.

El parámetro "metodo" especifica si se desea calcular las correlaciones con el método Pearson ("pearson"), Kendall ("kendall") o Spearman ("spearman")

El ejemplo abajo muestra la matriz de correlación para variables numéricas del conjunto de datos de COVID-19

In [14]:
corr_numericas = datos_covid.CorrelacionNumericas(metodo="pearson", variables=None)
corr_numericas

              Edad  Edad 2  Edad meses
Edad        1.0000  1.0000      0.9999
Edad 2      1.0000  1.0000      0.9999
Edad meses  0.9999  0.9999      1.0000

#### 10. Correlación de variables categóricas
El método "CorrelacionCategoricas" calcula una matriz de correlación para variables categóricas. Contiene los mismos parámetros que se explicaron en la Sección 7, para definir variables categóricas, pero incluye también el parámetro "metodo". Este especifica si se quiere calcular la matriz con el método Cramer ("cramer") o con la metodología Phik ("phik"), de la librería Phik de Python.

A continuación se calcula la matriz de correlación de variables categóricas para el conjunto de datos de COVID-19

In [15]:
corr_categoricas = datos_covid.CorrelacionCategoricas(metodo="phik")
corr_categoricas

,Atención,Sexo,Tipo,Estado,Tipo recuperación,Pertenencia etnica,Diccionario
Atención,1.000000,0.038193,0.195794,0.987038,0.941437,0.028540,0.000000
Sexo,0.038193,1.000000,0.094794,0.041878,0.025933,0.000000,0.000000
Tipo,0.195794,0.094794,1.000000,0.325888,0.320547,0.133658,0.000000
Estado,0.987038,0.041878,0.325888,1.000000,0.917328,0.067380,0.004040
Tipo recuperación,0.941437,0.025933,0.320547,0.917328,1.000000,0.051298,0.000000
Pertenencia etnica,0.028540,0.000000,0.133658,0.067380,0.051298,1.000000,0.002036
Diccionario,0.000000,0.000000,0.000000,0.004040,0.000000,0.002036,1.000000